### ISSUE TITLE
Routes for email verification

### ISSUE THREAD

**Issue by dralshehri** [frankie567/fastapi-users#106]
First of all, well done 👏🏼
I'm really impressed by the ideas, quality of code and documentation.

I'm thinking about adding email verification. Yes, it has some complexity, because you need to verify email after registration and when changing email but it's still essential for many apps.

I got inspired by `forgot-password` and `reset-password` routes. **Here is my idea**:

1. `generate-token` **route** that takes an email as input and returns a token.
2. `on_after_generate_token` **event** to handle email sending or what ever.
3. `verify-token` **route** that takes the generated token and returns a relevant status code.

Do you think it would work that way or there is a better way?

**Comment by frankie567** [comment]
Hi @dralshehri! Thank you very much for your support 😄

Indeed, I've thought about email validation and I agree it's an important feature. I think you are on the right track, it effectively matches the existing architecture while keeping it optional.

I'll think about it but this is definitely something that could be interesting to have 👍

**Comment by dralshehri** [comment]
That's great !

**Comment by lefnire** [comment]
Yes please to this! Definitely want it pre forgot/reset pw

**Comment by diegorosen** [comment]
Hi @dralshehri , do you have any update on this ? I was thinking on developing it before I found your great idea.

**Comment by dralshehri** [comment]
I will try to finish it by a week or two.

**Comment by dralshehri** [comment]
I've reviewed the code and docs to see if my suggestion is still valid or not. Let me do a deep dive in flows that might need email verification.

## Password Reset Flow:

The current implementation is supporting email verification through `after_forgot_password` handler but it might need to be clarified in documentation. For example:

1. User initiates the password reset by `forgot-password` route.
2. Using the `after_forgot_password` handler, we might send the user an email that has a link with JWT token in it (url path / query parameter).
3. Clicking the email link will take the user to a reset password form and the token will be available in the url to be utilized.
4. Submitting the form using `reset-password` route will verify token and reset password.

**To DO**
- [ ] Add an example to the docs on how to verify email after forgot password request.


## Register/Activate Flow:

The current implementation assumes the user `is_active` and email will not be verified. In order to verify email before activation we might need to follow this example:

1. User registers through `register` route and `is_active` is `False` by default.
2. Using the `after_register` handler, we might send the user an email that has a link with JWT token in it (url path / query parameter).
3. Clicking the email link will take the user to a page where the token will be available in the url to be utilized.
4. Sending a request using `activate` route (not implemented yet) will verify token and activate user.

**To DO**
- [ ] Change the default value for `is_active` in `BaseUser` model to be `False`.
- [ ] Generate an JWT token after creating the user in `register` route.
- [ ] Pass the token to `after_register` handler.
- [ ] Under `get_register_router()` function, create a new `activate` route that will verify the token and activate the user (similar to `reset-password` route).
- [ ] Try to avoid duplicated code with `reset.py` by moving the JWT decoding and verification code to `utils.py` for example.
- [ ] Add `ACTIVATE_USER_BAD_TOKEN` to `common.py`.
- [ ] Add tests.
- [ ] Add documentation.


Here is how I think the `register.py` should look like conceptually.
**❗️Be cautious. The following code was not tested**.

```py
from typing import Callable, Optional, Type, cast

import jwt
from fastapi import APIRouter, HTTPException, Request, status
from pydantic import UUID4

from fastapi_users import models
from fastapi_users.db import BaseUserDatabase
from fastapi_users.password import get_password_hash
from fastapi_users.router.common import ErrorCode, run_handler
from fastapi_users.utils import JWT_ALGORITHM, generate_jwt

ACTIVATE_USER_TOKEN_AUDIENCE = "fastapi-users:activate"


def get_register_router(
    user_db: BaseUserDatabase[models.BaseUserDB],
    user_model: Type[models.BaseUser],
    user_create_model: Type[models.BaseUserCreate],
    user_db_model: Type[models.BaseUserDB],
    activate_user_token_secret: str,
    activate_user_token_lifetime_seconds: int = 3600,
    after_register: Optional[Callable[[models.UD, Request], None]] = None,
) -> APIRouter:
    """Generate a router with the register and activate routes."""
    router = APIRouter()

    @router.post(
        "/register", response_model=user_model, status_code=status.HTTP_201_CREATED
    )
    async def register(request: Request, user: user_create_model):  # type: ignore
        user = cast(models.BaseUserCreate, user)  # Prevent mypy complain
        existing_user = await user_db.get_by_email(user.email)

        if existing_user is not None:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=ErrorCode.REGISTER_USER_ALREADY_EXISTS,
            )

        hashed_password = get_password_hash(user.password)
        db_user = user_db_model(
            **user.create_update_dict(), hashed_password=hashed_password
        )
        created_user = await user_db.create(db_user)

        token_data = {"user_id": str(created_user.id), "aud": ACTIVATE_USER_TOKEN_AUDIENCE}
        token = generate_jwt(
            token_data,
            activate_user_token_lifetime_seconds,
            activate_user_token_secret,
        )

        if after_register:
            await run_handler(after_register, created_user, token, request)

        return created_user

    @router.post("/activate")
    async def activate(token: str):
        try:
            data = jwt.decode(
                token,
                activate_user_token_secret,
                audience=ACTIVATE_USER_TOKEN_AUDIENCE,
                algorithms=[JWT_ALGORITHM],
            )
            user_id = data.get("user_id")
            if user_id is None:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail=ErrorCode.ACTIVATE_USER_BAD_TOKEN,
                )

            try:
                user_uuid = UUID4(user_id)
            except ValueError:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail=ErrorCode.ACTIVATE_USER_BAD_TOKEN,
                )

            user = await user_db.get(user_uuid)
            if user is None or user.is_active:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail=ErrorCode.ACTIVATE_USER_BAD_TOKEN,
                )

            user.is_active = True
            await user_db.update(user)
        except jwt.PyJWTError:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=ErrorCode.ACTIVATE_USER_BAD_TOKEN,
            )

    return router
```
---

😢 I apologize for not having the time to implement this completely. 

🙏🏼 @frankie567 would you check if we are on the right track? 

🙏🏼 @diegorosen (or anyone else) would you please takeover the task of completing this?

**Comment by frankie567** [comment]
Hello @dralshehri! Thank you for this thorough investigation. I still think it's a good feature, however, I wish it to be optional. 

I'll probably work on it myself as it'll probably require lot of changes. However, I'm a bit busy at the moment, so it'll probably take some time to be released.

**Comment by eddsalkield** [comment]
I have some time to work on this PR.  Is anyone else is currently handling it?  Just wanting to avoid duplicating the work here.

**Comment by frankie567** [comment]
I'm very happy to close this ticket 🎉 The feature will be released soon!

Thank you all for your help and guidance on this, especially @eddsalkield and @mark-todd who took on the job.

Cheers 👏

**Comment by frankie567** [comment]
@all-contributors add @dralshehri for ideas

**Comment by frankie567** [comment]
@all-contributors add @lefnire for ideas
