### ISSUE TITLE
"on before registration" event handler

### ISSUE THREAD

**Issue by MariusMez** [frankie567/fastapi-users#120]
Hi François,

I would like to secure my registration process using a recaptcha token which I need to validate before registering the user.

I wonder what is the better approach to process the token using the default fastapi-users /register route.

Maybe adding a new "on before registration" event handler could be a solution ? (if its possible to cancel the registration process in the case the token is invalid).

Or maybe you have a better suggestion for this usecase ? (I also try to avoid implementing this token validation using pydantic validators for my User object class)

**Comment by frankie567** [comment]
Hi @MariusMez!

Sorry for the response time! 

I understand your need. However, I'm not sure if a "on before registration" event would be the solution. From what I understand, it would need either to pass to the core controller (to perform the actual registration) or to return an error response itself when the token is invalid. I fear it would be a bit messy to understand and maintain.

Other solutions I think about for this:

* Implement it in a Pydantic validator, it sounds to me the most natural solution. I don't have all the background here, but why do you want to avoid it?
* [Create a middleware](https://fastapi.tiangolo.com/tutorial/middleware/). I think you could check in it that you are currently handling the `/register` route and perform your token validation. The good thing with this approach is that you could apply a CAPTCHA validation to any route you want.

What do you think?

**Comment by MariusMez** [comment]
Hi @ frankie567

No worries, I want to avoid the use of a Pydantic validator inside a User model because I don't want to link this user object to some security logic which for me is out of scope of this user object

And for this reason I think your idea to create a middleware could be a good solution for my needs, thank you for this suggestion!
