### ISSUE TITLE
How to use Oauth2 authentication in a Fastapi app ?

### ISSUE THREAD

**Issue by MariusMez** [frankie567/fastapi-users#122]
Just some thoughts as I try to understand how to use the Oauth2 implementation inside a fastapi app.

The official tutorial is here: https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/ and it is what I want to achieve. 

As I already use this nice fastapi-users plugin I assume I can use it to simplify the integration.

So I'm wondering if I need to use the Oauth2 Generic client (https://frankie567.github.io/httpx-oauth/oauth2/) to achieve this or just use the endpoint JWTAuthentication ? 

_(I understand the other usecases using Google/Github/ others OAuth providers and the documentation is clear about that)._

But for me the articulation to secure my API is a little confusing as I see some similar/overlapping methods between the official tutorial which use : `oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/token")` providing an 'Authorization' Button on the swagger api and the Fastapi-users implementation who apparently does'nt.

Also I don't understand in which usecases the OAuth2AuthorizeCallback is needed ? (https://frankie567.github.io/httpx-oauth/fastapi/)

**Comment by frankie567** [comment]
Hi @MariusMez!

I'm not sure what you try to achieve here 🙂The official tutorial you link here explains how you could implement an authentication system (with password hashing and all) ; which is precisely what `fastapi-users` do it.

So you don't have to do all this ; if you correctly setup `fastapi-users`, your API will be secured. The downside indeed is that there won't be a button in the Swagger documentation (see bug #68).

However, we don't support a full blown OAuth2 **server** (with client id, client secret generation, API scopes checks...). If this is what you want, I fear you'll have to implement it yourself.

The OAuth part provided here (along with `httpx-oauth`) is solely for implementing authentication with external services like Google or GitHub (the famous "Sign-in with..." button). It's an OAuth **client**.

As for `OAuth2AuthorizeCallback`, it's provided as a convenience for FastAPI users that would wish to implement external OAuth2 authentication themselves without using `fastapi-users`. If you use `fastapi-users`, we already provide routes to handle the authorization/callback flow (and [they internally use `OAuth2AuthorizeCallback`](https://github.com/frankie567/fastapi-users/blob/master/fastapi_users/router/oauth.py#L46-L53)).

**Comment by MariusMez** [comment]
Hi @frankie567 

Thank you for clarify my miscomprehension !
In fact as I haven't seen the bug #68 I thought my implementation was somewhat ineffective.

You can close this issue 👍
