### ISSUE TITLE
How to use sapper with fastapi-users

### ISSUE THREAD

**Issue by jet10000** [frankie567/fastapi-users#128]
Expect a complete example in the documentation,   it's better to use.

https://sapper.svelte.dev/

**Comment by frankie567** [comment]
I don't really understand how this framework could work with FastAPI?

**Comment by jet10000** [comment]
I found some links

https://www.nielsvandermolen.com/authentication-example-svelte-sapper/
https://www.reddit.com/r/sveltejs/comments/exm6r4/has_anyone_integrated_flask_django_with_svelte/

**Comment by jet10000** [comment]
https://github.com/acim/sapper-auth

**Comment by frankie567** [comment]
But what do you want to do? If you wish to implement authentication with Sapper, go on, but this has nothing to do with Python and FastAPI 🤷‍♂️

**Comment by jet10000** [comment]
OK, I continue to research, I want to use sapper and fastapi-users together.
