### ISSUE TITLE
Probem querying added user with psql

### ISSUE THREAD

**Issue by mahdikhashan** [frankie567/fastapi-users#178]
I have just added "Full example" to my fast api project with postgres.
After adding a user with cookie authentication, Trying to query and see recently added user by psql. when I query "user" table just see a table with single user column with a postgres value. 
P.S: authentication is working but when i try to logout cookie authed users, i can't.

fastapi: 0.54.1
fastapi-users: 0.8.0

**Comment by frankie567** [comment]
Hi @mahdikhashan!

Hmm... It's quite hard to understand your problem from here. Could you provide the SQL query you are doing and its result?

**Comment by mahdikhashan** [comment]
That's All I do in a pure terminal:

`(base) mahdi@x230:~$ sudo -u postgres psql
[sudo] password for mahdi: 
psql (10.12 (Ubuntu 10.12-0ubuntu0.18.04.1))
Type "help" for help.

postgres=# \c test
You are now connected to database "test" as user "postgres".
test=# \dt
             List of relations
 Schema |     Name      | Type  |  Owner   
--------+---------------+-------+----------
 public | doc_lessons   | table | postgres
 public | items         | table | postgres
 public | lessons       | table | postgres
 public | levels        | table | postgres
 public | quiz_answers  | table | postgres
 public | quizes        | table | postgres
 public | teachers      | table | postgres
 public | text          | table | postgres
 public | to            | table | postgres
 public | topics        | table | postgres
 public | user          | table | postgres
 public | users         | table | postgres
 public | video_lessons | table | postgres
(13 rows)

test=# select * from user;
   user   
----------
 postgres
(1 row)

test=#`

**Comment by frankie567** [comment]
Hum... Do you start from a clean database? Are you sure you have called `Tortoise.generate_schemas()` to create the tables and their columns?

**Comment by mahdikhashan** [comment]
No. I have added this to my existing database. I have used sqlalchemy.

**Comment by frankie567** [comment]
Hi @mahdikhashan! Is your problem solved? Can I close it?

**Comment by remykarem** [comment]
@mahdikhashan , you need to use quotation marks around the name `user` as it is a reserved keyword in Postgres.

```sql
select * from "user";
```

https://stackoverflow.com/a/21051549/4570466
