### ISSUE TITLE
user handling with HTML template

### ISSUE THREAD

**Issue by perfecto25** [frankie567/fastapi-users#188]
hello, how do I pass a ValidationError or 400 error back to the login.html template?

for example if user enters empty username or incorrect password, they just get a text return, 

```
1 validation error for Request
body -> password
  field required (type=value_error.missing)
Validation Error: 
```

How can I pass this error back to login.html template as a warning?

Thank you

**Comment by frankie567** [comment]
Hi @perfecto25!

FastAPI is intended to be used as a REST API, not a traditional web framework like Django that generates HTML response.

The correct way to do this is to write a bit of JavaScript in your page to handle the form submission, handle the response and make the redirection.

**Comment by UnoYakshi** [comment]
@frankie567, so there is no native way to check in Jinja2, for example, that the user is logged in?

```jinja2
{% if request.user.is_authenticated %}
...
{% endif %}
```

**Comment by frankie567** [comment]
> @frankie567, so there is no native way to check in Jinja2, for example, that the user is logged in?
> 
> ```jinja2
> {% if request.user.is_authenticated %}
> ...
> {% endif %}
> ```

You can use the `current_user` dependency with the `optional` flag  and pass the result in your template context. Then, you can check if it's `None` or not.

**Comment by UnoYakshi** [comment]
I feel stupid I didn't figure out this solution. Thank you, @frankie567!
