### ISSUE TITLE
Seperate routers for login and users

### ISSUE THREAD

**Issue by system123** [frankie567/fastapi-users#189]
Having the login, register etc. endpoints tied to the users router seems a bit unnatural, especially if the api is versioned. It is nicer to have these endpoints on the root, and then all user CRUD functionality on a `users/` endpoint. 

The way I see this is that fastapi_users should contain a `auth_router` and a `user_router` such that they can be prefixed separately.

**Comment by frankie567** [comment]
Hi @system123!

Thank you for your feedback. I agree that this would make more sense and make lot of things easier. I'll think about it :)

Cheers!
