### ISSUE TITLE
ImportError: cannot import name 'models' from 'fastapi_users' (./fastapi_users.py)

### ISSUE THREAD

**Issue by rodgerthat3000** [frankie567/fastapi-users#192]
Hi,

I am pretty new to fastapi. 
Sorry might sound really silly but here is what I did:

I tried this for both SQLAlchemy and Tortoise ORM and got the same result.

I created a new file main.py under fastapi_users directory and copied the example, from:
https://frankie567.github.io/fastapi-users/configuration/databases/sqlalchemy/

For SQLAlchemy I changed the following line:
engine = sqlalchemy.create_engine(
    DATABASE_URL, connect_args={"sqlite:///": False}

As I am testing it with SQLite.
I ran the uvicorn command line: uvicorn main:app --reload

Then I get the error:
 module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 4, in <module>
    from fastapi_users import FastAPIUsers, models
  File "./fastapi_users.py", line 7, in <module>
    from fastapi_users import models
ImportError: cannot import name 'models' from 'fastapi_users' (./fastapi_users.py)

I tried it with tortoise and get the same error, but I am still confused with the following line:
register_tortoise(app, modules={"models": ["path_to_your_package"]})
what path do I supply there I checked another post for Tortoise ORM and it just stated like this:
register_tortoise(app, modules={"models": ["models"]})

I am in the correct Virtualenv - (fastapi-users) and also I checked pip freeze and it appears all the correct modules are there. There is quite a lot of them, for tortoise ORM I installed the 3 others stated on the docs of fastapi_users.

Can someone help me please? I am including my main.py file --> had to rename it to main.txt for github!
[main.txt](https://github.com/frankie567/fastapi-users/files/4642297/main.txt)

**Comment by frankie567** [comment]
Hi @rodgerthat3000!

Well, that is quite a bunch of information 🙃There are several things that could explain why it doesn't work:

* You said you created a `fastapi_users` directory. You can't do that, otherwise when you import it, it will take precedence over the real `fastapi_users` package that you installed with `pip`. You should rename it `myproject` or something like that.
* I don't understand why you wrote this:
```py
engine = sqlalchemy.create_engine(
    DATABASE_URL, connect_args={"sqlite:///": False}
)
```
The default line in the example is working well:
```py
engine = sqlalchemy.create_engine(
    DATABASE_URL, connect_args={"check_same_thread": False}
)
```

Concerning your question about Tortoise. What I mean is that you should provide the path to the Python modules containing your Tortoise models. So for example if you put your models in a file named `models.py`, you can write `register_tortoise(app, modules={"models": ["models"]})`. You should take a look at the Tortoise ORM documentation : https://tortoise-orm.readthedocs.io/en/latest/getting_started.html

**Comment by rodgerthat3000** [comment]
Hi Frankie thanks so much for your help. I think I had some issues with my pc as well as python was acting a bit funny I am going to try it again and Ill let you know.

**Comment by rodgerthat3000** [comment]
Hi Frankie,

No luck I have hit another roadblock so below is my file stucture:
![image](https://user-images.githubusercontent.com/44711934/82560661-3479ba00-9bb5-11ea-87d6-dfbf102a72a1.png)

For some reason its not picking up my models?

When I ran the uvicorn 

This is my weird error:
File "./fastapi_users.py", line 6, in <module>
    from fastapi_users import models
ImportError: cannot import name 'models' from 'fastapi_users' (./fastapi_users.py)

It should be reading all the files correctly now, weird why it doesnt?

Appreciate any help thanks.

**Comment by frankie567** [comment]
Hum... Why did you clone the repository ? It's not a base project for you to use, it's a library you have to install, just like FastAPI. I think you should start with the basics:

* Follow the FastAPI tutorial (which is awesome) : https://fastapi.tiangolo.com/tutorial/
* Once you have a FastAPI project setup, you can start the installation process of FastAPI users : https://frankie567.github.io/fastapi-users/installation/
