### ISSUE TITLE
How to make custom routes require user auth?

### ISSUE THREAD

**Issue by chillz561** [frankie567/fastapi-users#206]
Hello I have looked over the document and not really sure if I missed it but. I am trying to use Jwt with mongodb to create a project how can I use fastapi users to prevent access to custom routes. For example someone who is not logged in and authenticated cannot view a /orders , /profile,  /settings or any custom  page that requires logged in users?

**Comment by frankie567** [comment]
You should use the dependency callables : https://frankie567.github.io/fastapi-users/usage/dependency-callables/

**Comment by chillz561** [comment]
@frankie567 Thank you I was looking for that in the docs don't know how I missed it. Thanks for the help and awesome project
