### ISSUE TITLE
Incompatable with FastAPI 0.55.0

### ISSUE THREAD

**Issue by galvakojis** [frankie567/fastapi-users#207]
`ERROR: fastapi-users 1.1.0 has requirement fastapi<0.55.0,>=0.54.0, but you'll have fastapi 0.55.1 which is incompatible.`

no plans to update it?

**Comment by frankie567** [comment]
I was planning to do it yes ! I'll do it right away 😉

**Comment by frankie567** [comment]
Fixed in [v1.1.1](https://github.com/frankie567/fastapi-users/tree/v1.1.1).
