### ISSUE TITLE
trying to migrate 0.8.x ➡️ 1.0.x

### ISSUE THREAD

**Issue by galvakojis** [frankie567/fastapi-users#208]
I am trying to migrate from old version but suggested script for MongoDB 
```
db.getCollection('users').find().forEach(function(user) {
  var uuid = UUID(user.id);
  db.getCollection('users').update({_id: user._id}, [{$set: {id: uuid}}]);
});
```
gives an error

>  [thread1] Error: Invalid UUID string: UUID("49caa9b2-a1f1-4459-bc4c-7e5a5d7d88e1") :

so later i created new account and  clearly see, that something have changed 
![image](https://user-images.githubusercontent.com/17315578/83019718-189c6b00-a030-11ea-8b02-ab9f3d3222b5.png)

**Update**
I managed  to update user in DB(?) well  I think so, but nothing have changed(still same as showed in first picture)
![image](https://user-images.githubusercontent.com/17315578/83020184-cd368c80-a030-11ea-8616-f89f95c34151.png)
using admin user (which one was created in old version), I can't login, using a new one I can

**Comment by galvakojis** [comment]
found the issue
instead of this:
`var uuid = UUID(user.id);`
i needed to use this:
var uuid = BinData(3, UUID(user.id).base64());

**Comment by frankie567** [comment]
It works on my MongoDB version. Which MongoDB version are you using?

**Comment by galvakojis** [comment]
mongo:4.2.3

**Comment by galvakojis** [comment]
yeah, also tried to write some usable migration file, but until this moment no success :/

**Comment by frankie567** [comment]
Ok, I get it. Your MongoDB connection is not set to use the new UUID standard, it's using the legacy format (which is still the default). I explain it here in the doc : https://frankie567.github.io/fastapi-users/configuration/databases/mongodb/#setup-database-connection-and-collection

But this is something I definitely should add in the migration documentation. I'll do this.

To solve your problem:
* If you still have a backup of you DB with string-ID, you should apply the script I provide.
* If not, you should convert legacy-UUID to standard-UUID. Something like:

```js
db.getCollection('users').find().forEach(function(user) {  
    var uuid = new BinData(4, user.id.base64()); // Notice the 4 instead of 3
    db.getCollection('users').update({_id: user._id}, [{$set: {id: uuid}}]); 
});
```
* Configure your MongoDB connection with standard-UUID representation as stated in the doc : https://frankie567.github.io/fastapi-users/configuration/databases/mongodb/#setup-database-connection-and-collection

I would also recommend that you try [Robot 3T](https://robomongo.org/download) as it clearly tells if a field is a UUID or Legacy UUID.

**Comment by galvakojis** [comment]
thank you, frankie.
Here I will try to write my steps:
used old backup file to restore DB.
added that missing line from here` uuidRepresentation="standard"`
https://frankie567.github.io/fastapi-users/configuration/databases/mongodb/#setup-database-connection-and-collection
Well now  it is working as before. 
(Except your script, same error)
![image](https://user-images.githubusercontent.com/17315578/83114555-c57af480-a0d1-11ea-92e0-fc467be49ebe.png)

**Comment by frankie567** [comment]
Which editor are you using to execute your queries?

**Comment by galvakojis** [comment]
All work fine!
Mongo shell.

**Comment by frankie567** [comment]
Oh, okay, sorry I misread your answer 😃 Glad we worked it out !

Cheers!

**Comment by galvakojis** [comment]
Thank you once again, if you find how to same thing in python (not in mongo shell), please share it

**Comment by frankie567** [comment]
Sure! Should be something like:

```py
import uuid

import motor.motor_asyncio


async def migrate_uuid():
    client = motor.motor_asyncio.AsyncIOMotorClient(
        DATABASE_URL, uuidRepresentation="standard"
    )
    db = client["database_name"]
    users = db["users"]

    async for user in users.find({}):
        await users.update_one(
            {"_id": user["_id"]},
            {"$set": {"id": uuid.UUID(user["id"])}},
        )
```

**Comment by frankie567** [comment]
I've added this information in the [migration documentation](https://frankie567.github.io/fastapi-users/migration/08_to_10/). Thank you for raising this point 😃

**Comment by galvakojis** [comment]
Hello frankie

> Sure! Should be something like:
> 
> ```python
> import uuid
> 
> import motor.motor_asyncio
> 
> 
> async def migrate_uuid():
>     client = motor.motor_asyncio.AsyncIOMotorClient(
>         DATABASE_URL, uuidRepresentation="standard"
>     )
>     db = client["database_name"]
>     users = db["users"]
> 
>     async for user in users.find({}):
>         await users.update_one(
>             {"_id": user["_id"]},
>             {"$set": {"id": uuid.UUID(user["id"])}},
>         )
> ```

it returns legacy UUID, not a standard one
