### ISSUE TITLE
msg": "value is not a valid uuid" after update

### ISSUE THREAD

**Issue by roshmath** [frankie567/fastapi-users#209]
Hi,
     I recently updated my package to the newest version and after readding register routes I'm getting the error `msg": "value is not a valid uuid",` I assume this has something to do with PyDantic's validation so I'm wondering how to fix this.

**Comment by frankie567** [comment]
Hi @roshmath!

Did you follow the [migration path](https://frankie567.github.io/fastapi-users/migration/08_to_10/)?

**Comment by roshmath** [comment]
I didn't actually see anything there that applied to my project.

As of right now I'm using `databases[sqlite]` and `fastapi-users[sqlalchemy]`

I ended up just fully dropping the database and starting from scratch but am still getting the error. When inspecting the **id** column of the **user** table, it is type `CHAR(36)` which I believe is correct.

**Comment by frankie567** [comment]
Could you provide the request your are doing and the full response? It'll help us understand where the error comes from.

**Comment by roshmath** [comment]
Using `/users/register` here is the default **"Try it Out**" request body:

```
{
  "id": "string",
  "email": "user@example.com",
  "is_active": true,
  "is_superuser": false,
  "password": "string"
}
```

and here is the response:

```
{
  "detail": [
    {
      "loc": [
        "body",
        "user",
        "id"
      ],
      "msg": "value is not a valid uuid",
      "type": "type_error.uuid"
    }
  ]
}
```

We're able to get around this by taking out `"id": "string",` in the initial POST.

**Comment by galvakojis** [comment]
jus remove this line from post request
`"id": "string",`

**Comment by roshmath** [comment]
[UUID in SQLite](https://gist.github.com/gmolveau/7caeeefe637679005a7bb9ae1b5e421e)

Found an implementation of UUID in sqlite that could be of use
