### ISSUE TITLE
[feature request] handling secret

### ISSUE THREAD

**Issue by nullhack** [frankie567/fastapi-users#216]
I think the webserver secret should have a more secure way to handle the secret variable. Examples like the ones defined on the [website](https://frankie567.github.io/fastapi-users/configuration/full_example/) suffer from the issue described [here](https://blog.paradoxis.nl/defeating-flasks-session-management-65706ba9d3ce).

I can think in two ways of doing It:

First: change the examples to generate a random number every time the app starts (easy to put on examples. If the comments agree I can do this easily).

Second: a more complicated approach would be including It on the API, creating a table on the database that stores a strong encrypted key that needs to be decrypted somehow when running the webserver (one way would be using a db_secret='SECRET' to decrypt the key from db. This would be secure even if no one changes the password because the password stored is generated randomly and is secure. But of course, if someone has access to the table, could retrieve the key, but the surface area is much smaller already).

**Comment by frankie567** [comment]
Thank you for raising this point @nullhack. I get the point of the article you mention but the way I see it, developers should be responsible of choosing a strong secret and keep it safe. This approach is widely used in big and battle-tested frameworks like Flask, [Django](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-SECRET_KEY), [Ruby on Rails](https://guides.rubyonrails.org/security.html#session-storage)...

However, I agree this should be mentioned in a warning/danger notice in the documentation to raise developers attention that they should take extra-care about this.
