### ISSUE TITLE
[feature request] first user is superuser

### ISSUE THREAD

**Issue by nullhack** [frankie567/fastapi-users#218]
Would be helpful if the first registered user is automatically assigned as superuser.

**Comment by frankie567** [comment]
Well, I'm not convinced by automatically making the first user a superuser. This could be a bit surprising/dangerous in some cases.

The ideal way would be to have a CLI (with [tiangolo's Typer](https://github.com/tiangolo/typer) ideally), like the Django one. But this is quite some work to do!

**Comment by SelfhostedPro** [comment]
@frankie567 could you provide instructions in documentation on how to add a user in a similar way as to how you do in the register API so that if we want to do this we are able to easily?
