### ISSUE TITLE
[feature request] scope to limit router usage

### ISSUE THREAD

**Issue by nullhack** [frankie567/fastapi-users#219]
Would be nice if routes were limited (or capable of) by some scope.
For example: to register a user, we could set something like:

```
app.include_router(
    fastapi_users.get_register_router(),
    prefix="/auth",
    tags=["auth"],
    scope=["user:register"]
)
```

Then, if the token has the scope or is a superuser, It's allowed to use the router.

This feature depends on https://github.com/frankie567/fastapi-users/issues/218 or else the first user would need to be created directly on database.

**Comment by frankie567** [comment]
I'll make quite the same comment as in #217 : a scope approach could be interesting, but I don't think it's in the scope of this project. I think we can wire things pretty easily between `fastapi-permissions` (for example) and `fastapi-users` with dependency callables.
