### ISSUE TITLE
`No matching distribution found for fastapi-users==2.0.1

### ISSUE THREAD

**Issue by stodge** [frankie567/fastapi-users#248]
I don't know if I'm just having a moment, but I can't for the life of me install fastapi-users:

`No matching distribution found for fastapi-users==2.0.1 (from -r /requirements.txt (line 4))`

Thanks

**Comment by frankie567** [comment]
Everything seems fine, I did a fresh install on a clean virtualenv without cache ; all is working. Maybe you have a custom pip configuration which does not fetch libraries from PyPI?

**Comment by stodge** [comment]
I'm trying to install it in a docker file, but I can successfully install other packages via pip. Weird. Thanks for the reply.

**Comment by frankie567** [comment]
No problem! Unless you have very specific dependencies, I guess you should be able to safely bump your base Docker image to Python 3.7 without encountering any issue.

**Comment by stodge** [comment]
Yes, I managed to bump up to a newer version of Python. Thanks.

**Comment by lefnire** [comment]
I'm using [tensorflow/tensorflow:latest-gpu](https://hub.docker.com/layers/tensorflow/tensorflow/latest-gpu/images/sha256-a0d274b584f757eae4fc82562daf52e608a7190b96a86a4e547ce9ae77f855e9?context=explore) which uses 3.6.9 (come on Tensorflow... so close...) and I'm pretty tied to it at present. Does fastapi-users use 3.7 features not available in 3.6? If so I'll do the work finding a way around; if not, possible to bump requirement down?

**Comment by lefnire** [comment]
I was able to switch to [pytorch/pytorch](https://hub.docker.com/layers/pytorch/pytorch/1.6.0-cuda10.1-cudnn7-runtime/images/sha256-9c3aa4653f6fb6590acf7f49115735be3c3272f4fa79e5da7c96a2c901631352?context=explore) and manually `RUN pip install tensorflow`; was doing the reverse (want the Dockerfile since it sets up CUDA/cuDNN). pytorch/pytorch uses 3.7.7. Phew!
