### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jorgerpo** [frankie567/fastapi-users#251]
Hello Frankie 
This is a great piece of code for FastAPI

I'd like to know how you envision the Roadmap for fastapi-users

Thank you

**Comment by frankie567** [comment]
Hi @jorgerpo!

Well, I think we are feature-complete now. I do not wish to add more features or complexity. My goal was to provide a quick and easy-to-use authentication system like the one you can find in Django for example.

So here is what I see for the near-future :
* Follow closely FastAPI evolutions
* Improve JWT authentication backend. I feel here some things are not right.
* Become the de-facto standard for FastAPI authentication 😬 

However, I would be open to help/contribute on libraries that would implement new features on top of FastAPI Users.
