### ISSUE TITLE
JWT token refresh

### ISSUE THREAD

**Issue by moreinhardt** [frankie567/fastapi-users#253]
Hi, thanks for the great package and documentation first of all!

However, I was wondering if I missed something or if the JWT logic is missing a `/refresh_token` router?

How can I make sure the user doesn't need to supply the password again when the token expires? I was planning on automatically refreshing it as long as it is still valid.

**Comment by frankie567** [comment]
Hi! 

Currently, there is no logic to refresh a JWT token. However, you can implement it quite easily, e.g.:

```py
from fastapi import Depends, Response


@router.post("/auth/jwt/refresh")
async def refresh_jwt(response: Response, user=Depends(fastapi_users.get_current_active_user)):
    return await jwt_authentication.get_login_response(user, response)
```

**Comment by moreinhardt** [comment]
Wow thanks for the ultra fast response!

That's really neat indeed. I think that would be really valuable to add to the docs. Do you agree?

**Comment by frankie567** [comment]
Hey, why not 👍

**Comment by moreinhardt** [comment]
Great work, thank you!!

**Comment by ronek22** [comment]
> Hi!
> 
> Currently, there is no logic to refresh a JWT token. However, you can implement it quite easily, e.g.:
> 
> ```python
> from fastapi import Depends, Response
> 
> 
> @router.post("/auth/jwt/refresh")
> async def refresh_jwt(response: Response, user=Depends(fastapi_users.get_current_active_user)):
>     return await jwt_authentication.get_login_response(user, response)
> ```

Is it possible in v11?

**Comment by mike-pisman** [comment]
> > Hi!
> > Currently, there is no logic to refresh a JWT token. However, you can implement it quite easily, e.g.:
> > ```python
> > from fastapi import Depends, Response
> > 
> > 
> > @router.post("/auth/jwt/refresh")
> > async def refresh_jwt(response: Response, user=Depends(fastapi_users.get_current_active_user)):
> >     return await jwt_authentication.get_login_response(user, response)
> > ```
> 
> @frankie567 Is it possible in v11?
 
Not sure if that's the right way to do so, but it works for me(I get a new token in my DB). If you use JWT, you would have `get_jwt_strategy`, etc

```
@router.post("/auth/jwt/refresh")
async def refresh_jwt(response: Response,
                      token_db=Depends(get_access_token_db),
                      user=Depends(get_current_active_user)):

    res = await jwt_backend.login(strategy=get_database_strategy(token_db), user=user)
    return res
```

**Comment by ronek22** [comment]
Thank you, that solution works. However, it appears that we can only refresh the token prior to the access token's expiration. In order to address this limitation, it may be necessary for us to implement a service worker in the frontend. I must admit, I'm a bit surprised that a popular project like this doesn't offer refresh tokens out of the box.

**Comment by mike-pisman** [comment]
> Thank you, that solution works. However, it appears that we can only refresh the token prior to the access token's expiration. In order to address this limitation, it may be necessary for us to implement a service worker in the frontend. I must admit, I'm a bit surprised that a popular project like this doesn't offer refresh tokens out of the box.

I recommend you take a look at #350 and [fastapi-jwt-auth](https://indominusbyte.github.io/fastapi-jwt-auth/usage/refresh/) library

You basically need generate 2 tokens, one for API and the other for refreshing the first token. Also you will need to send a different response on login/refresh; This might require rewriting Login function
i.e.
Response Schema
``` python
class LoginOutput(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"
    expires: int = 3600
```

Login route
``` python
@router.post(
    "/jwt/login",
    name=f"auth:{jwt_backend.name}.login",
    responses=login_responses,
)
async def login(
    request: Request,
    credentials: OAuth2PasswordRequestForm = Depends(),
    user_manager: BaseUserManager[models.UP, models.ID] = Depends(get_user_manager),
    strategy1: Strategy[models.UP, models.ID] = Depends(jwt_backend1.get_strategy),
    strategy2: Strategy[models.UP, models.ID] = Depends(jwt_backend2.get_strategy)
):
    user = await user_manager.authenticate(credentials)

    if user is None or not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=ErrorCode.LOGIN_BAD_CREDENTIALS,
        )
    token1 = await strategy1.write_token(user)
    token2 = await strategy2.write_token(user)

    return AuthSchemas.LoginOutput(access_token=token1, refresh_token=token2)
```
