### ISSUE TITLE
difficulties in OAuth2 authorization

### ISSUE THREAD

**Issue by darkdkl** [frankie567/fastapi-users#258]
Greetings.
just starting to learn FastAPI please do not judge strictly.
I need to authorize users through social networks (OAuth2)
example from documentation [Tortoise ORM Full example ](https://frankie567.github.io/fastapi-users/configuration/oauth/)
with GoogleOAuth2 for authentication requires authentication_backend
I tried to transmit the jwt_authentication string too .... please direct to the correct path
thank

**Comment by frankie567** [comment]
Hey there!

Could you describe in more details the issue you are experiencing? Do you have an error or something?

**Comment by darkdkl** [comment]
Greetings.
I can't figure out what is expected in this field ... backend name? I tried and JWTAuthentication and jwtauthentication .... perhaps due to the fact that I translate the documentation with the googl translator ... I am missing something ... then, I'm sorry .. but I can't find the answer .... maybe information on the link [routers documentation(page not found) ](https://frankie567.github.io/fastapi-users/configuration/authentication/routers/index.md) ? but the page is missing ...
![auth_back](https://user-images.githubusercontent.com/5443644/87691876-c6f0a100-c793-11ea-806f-0ed517a14898.png)
sorry if the question is too simple

**Comment by frankie567** [comment]
Ok I see! Maybe it's not very clear in the documentation. You need to put the `name` of your authentication backend. By default, for JWT, it's simply `jwt`. You can read explanations about this here: https://frankie567.github.io/fastapi-users/configuration/authentication/jwt/#configuration

Hope it'll help!

**Comment by darkdkl** [comment]
URAAAAAAAAAA, .....
thank you ... I suffered for several days ... trying to find the answer

**Comment by frankie567** [comment]
I'll improve the documentation about this :)

Cheers!
