### ISSUE TITLE
Better and safer regex for email retrieving 

### ISSUE THREAD

**Issue by MariusMez** [frankie567/fastapi-users#261]
Hello :-)

A simple proposal to improve this line: 

https://github.com/frankie567/fastapi-users/blob/1b6c832b28dc8e3b082765bb2e970cbd759fc0ce/fastapi_users/db/mongodb.py#L32

Currently this doesn't work (tested using mongodb) with emails using special characters like : 'john.doe+something@email.com'

This line could be safer written, escaping the email of any special characters which might affect the regex match (like the '+') and by matching the exact string: 
`import re`
`user = await self.collection.find_one({'email': re.compile('^' + re.escape(email) + '$', re.IGNORECASE)})`

**Comment by frankie567** [comment]
I knew while writing this it would cause issues. I was surprised that MongoDB didn't have a simple case-insensitive search operator. Anyway, thank you for the fix, I'll look into it!

**Comment by MariusMez** [comment]
Yes for that case-insensitive search I think in mongodb we need to create a specific index with a specific collation...

**Comment by frankie567** [comment]
Sounds so 😅 Do you have any pointers to doc or articles that would explain how to implement this?

**Comment by MariusMez** [comment]
Related official doc: https://docs.mongodb.com/manual/core/index-case-insensitive/

But I think you could just keep the updated regex method as it does the job.

**Comment by frankie567** [comment]
After all, I went over the collation index path. It doesn't add lot of complexity, and I think it'll be more efficient in the long-run. By default, the adapter instantiates a collation with sensible defaults, but we let the possibility to pass a custom one if needed.

**Comment by frankie567** [comment]
@all-contributors add @MariusMez  for bug, ideas
