### ISSUE TITLE
Extend user model and migrations with alembic

### ISSUE THREAD

**Issue by Lepiloff** [frankie567/fastapi-users#262]
Hi!
At my project im using fastapi, sqlalchemi, databases and alembic. I'm trying to add a library fastapi-user,  but I faced the problem of using the syntax of model definition as in the library of databases and migrations to alembic. 
What am I talking about... 

At the db.py I create `metadata` and `database` objects
**db.py**

```
from databases import Database
from sqlalchemy import MetaData, create_engine

DATABASE_URL = "postgresql://......."

engine = create_engine(DATABASE_URL)
metadata = MetaData()
database = Database(DATABASE_URL)
```
Create any models using `databases` syntax

**models.py**

```
from sqlalchemy import Table, Column, Integer, String, DateTime
from sqlalchemy.sql import func
from db import metadata

notes = Table(
    "notes",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("test_field", String(50)),
    Column("title", String(50)),
    Column("description", String(50)),
    Column("created_date", DateTime, default=func.now(), nullable=False),
)

```
As one of the Table arguments, I pass the metadata object

Then in the alembic `env` file I pass models (`notes`) and `metadata` and redefine `target_metadata` variable

**env.py**

```
from models.notes import notes
from db import DATABASE_URL, metadata

target_metadata = metadata
```
And run 
`alembic revision --autogenerate`

At this stage, everything is working as it should. Now I should add the user model ..

How do I inherit the new UserTable class from SQLAlchemyBaseUserTable ? If I try smth like 

```
users = Table(
    "usertable",
    metadata,
    SQLAlchemyBaseUserTable,
    Column("name", String(50)),
    Column("created_date", DateTime, default=func.now(), nullable=False),
)
```
**env.py**
```
from models.notes import notes
+ from models.users import users
from db import DATABASE_URL, metadata
...
target_metadata = metadata
```

I got an error
`sqlalchemy.exc.ArgumentError: 'SchemaItem' object, such as a 'Column' or a 'Constraint' expected, got <class 'fastapi_users.db.sqlalchemy.SQLAlchemyBaseUserTable'>`

What is the right way to add/extend a user model?

**Comment by frankie567** [comment]
Hey there!

I have to admit I'm not very experienced in SQLAlchemy and Alembic. In `fastapi_users` implementation, we use the declarative way. According to [SQLAlchemy docs](https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/basic_use.html#accessing-the-metadata), there is a way to melt the two:

```py
from sqlalchemy.ext.declarative import declarative_base

# Declare a base from your metadata
Base: DeclarativeMeta = declarative_base(metadata=metadata)

# Create the User table with the class style
class UserTable(Base, SQLAlchemyBaseUserTable):
    # Add your columns here
    name = Column(String(50))
```

I've not tested it but this sounds promising.

**Comment by Lepiloff** [comment]
Your code works, thank you for your help.

**Comment by bazakoskon** [comment]
Is there any example or documentation on how to add more models - tables using fastapi-users, apart from the prebuilt User model?

**Comment by bfontaine** [comment]
@bazakoskon Could you be a bit more specific?
