### ISSUE TITLE
Register user error

### ISSUE THREAD

**Issue by Lepiloff** [frankie567/fastapi-users#265]
Hey there!

Then I try to register new user `http://127.0.0.1:8000/auth/register `

I get an error
```
  File "/home/y700/Env/text-detector/lib/python3.7/site-packages/fastapi_users/db/sqlalchemy.py", line 123, in get_by_email
    query = self.users.select().where(
AttributeError: 'str' object has no attribute 'select'
```
The changes that I made

Extend user model
**model.py**
# Custom user
```
class UserTable(Base, SQLAlchemyBaseUserTable):
    name = Column(String(50))

users = UserTable.__tablename__
```
And add fields `name` to pydantic file 
**schemas.py**

```
from fastapi_users import models

class User(models.BaseUser):
    name: str

class UserCreate(models.BaseUserCreate):
    name: str

class UserUpdate(User, models.BaseUserUpdate):
    name: str

class UserDB(User, models.BaseUserDB):
    name: str
```

Is it right idea to add field name to each pydantic clases?

The main question is, what is the cause of the error that occurs?

**p.s.**
The same result after run
`http://127.0.0.1:8000/auth/jwt/login`

**Comment by frankie567** [comment]
Hey!

The problem is here:

```py
users = UserTable.__tablename__  # This a string representing the table name
```

You should write:

```py
users = UserTable.__table__  # This is the actual table instance on which we can make requests
```

As for adding the field to each Pydantic class, yes, you can do it like this. Actually, you don't have to repeat them when you inherit from `User`, but it doesn't do any harm.

**Comment by Lepiloff** [comment]
@frankie567 Great! it works? thank you
