### ISSUE TITLE
Create a database adaptor for AWS DynamoDB

### ISSUE THREAD

**Issue by SkullTech** [frankie567/fastapi-users#271]
It can be added using [`boto3`](https://github.com/boto/boto3) or even something higher level such as [`pynamodb`](https://github.com/pynamodb/PynamoDB). What do you think? If you wanna do this I can help you if you need. Or I can take this up myself if you are not familiar with AWS, with some help from you I can do this.

**Comment by frankie567** [comment]
Hi @SkullTech!

Interesting indeed! Have you heard of an `async` implementation of the client? One of the benefit of `fastapi` and friends is to be `async`-first, so it would be cool to have it as async also.

**Comment by SkullTech** [comment]
Yeah implementing this using `async` libraries would be great indeed. I looked around and it seems [`aioboto3`](https://github.com/terrycain/aioboto3)—which uses [`aiobotocore`](https://github.com/aio-libs/aiobotocore) as a backend—is the best one there is.

**Comment by SkullTech** [comment]
@frankie567 Should I go ahead and start implementing it? I can send a pull request once I'm done.

**Comment by frankie567** [comment]
Sure go on :)

What you have to do is:

* Create a class that inherits from and implement the required methods of [`BaseUserDatabase`](https://github.com/frankie567/fastapi-users/blob/master/fastapi_users/db/base.py)
* Create a test file on the model of the others : https://github.com/frankie567/fastapi-users/blob/master/tests/test_db_sqlalchemy.py In the case of DynamoDB, I think you'll have to mock the internal calls made by `aioboto3`.
* Write the doc : https://github.com/frankie567/fastapi-users/blob/master/docs/configuration/databases/mongodb.md

Cheers!

**Comment by XWilliamY** [comment]
Is this still being worked on? I see that a new context manager is opened every time a method of the database adapter is called, which doesn't look to be super efficient.
I was wondering if we could create an AsyncExitStack on startup and have the exit coroutine in the shutdown event [pretty much like the last example in the aioboto3 docs](https://aioboto3.readthedocs.io/en/latest/usage.html)
[using startup and shutdown events](https://fastapi.tiangolo.com/advanced/events/).

```python
@app.on_event("startup")
async def startup_event():
    context_stack = contextlib.AsyncExitStack()
    app.context_stack = context_stack

    app.dynamodb_resource = await context_stack.enter_async_context(
        aioboto3.resource("dynamodb", region_name="eu-north-1")
    )

    app.table = await app.dynamodb_resource.Table("user_v9")


@app.on_event("shutdown")
async def shutdown_event():
    await app.context_stack.aclose()
```

We can then pass this app.table object to the database adapter.
