### ISSUE TITLE
Use email as field name instead of username

### ISSUE THREAD

**Issue by diflores** [frankie567/fastapi-users#273]
Hello, Frankie!

First, I want to thank you for this fantastic job; it has helped me a lot in a few projects (both personal projects and for school). I'm posting this issue because in `auth/jwt/login`, I want to keep using email authentication, but I want to use "email" as the name of the corresponding field, instead of the current name, which is "username". I would like to accomplish the following:

```
POST /auth/jwt/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded
accept: application/json
Host: 127.0.0.1:8000
Connection: close
User-Agent: Paw/3.1.10 (Macintosh; OS X/10.15.4) GCDHTTPRequest
Content-Length: 39

email=example%40uc.cl&password=hellohello123
```

Instead of the current:
```
POST /auth/jwt/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded
accept: application/json
Host: 127.0.0.1:8000
Connection: close
User-Agent: Paw/3.1.10 (Macintosh; OS X/10.15.4) GCDHTTPRequest
Content-Length: 39

username=example%40uc.cl&password=hellohello123
```

What should I overload in the source code to rename the "username" field to "email" on that login request?

Any help would be much appreciated.

**Comment by frankie567** [comment]
Hello 👋

Glad it helps 😃

Well the issue with this is that it internally uses the [OAuth2 flow provided by FastAPI](https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/#get-the-username-and-password) with the [OAuth2PasswordRequestForm class](https://github.com/tiangolo/fastapi/blob/master/fastapi/security/oauth2.py#L13): it closely follows the OAuth2 spec and so defines the field as `username`. From my experience, it has never caused any particular issue, but I would be interested why you specifically need the field to be named `email` 🙂

Now, to solve this, I fear there is no easy way. You best bet is to reimplement the [`get_auth_router` method](https://github.com/frankie567/fastapi-users/blob/master/fastapi_users/router/auth.py). I think you can write something like this (not tested):

```py
from fastapi import APIRouter, Depends, Form, HTTPException, Response, status
from fastapi.security import OAuth2PasswordRequestForm

from fastapi_users import models
from fastapi_users.authentication import Authenticator, BaseAuthentication
from fastapi_users.db import BaseUserDatabase
from fastapi_users.router.common import ErrorCode


def get_auth_router(
    backend: BaseAuthentication,
    user_db: BaseUserDatabase[models.BaseUserDB],
    authenticator: Authenticator,
) -> APIRouter:
    """Generate a router with login/logout routes for an authentication backend."""
    router = APIRouter()

    @router.post("/login")
    async def login(
        # Ask for the two fields in the request
        response: Response, email: str = Form(), password: str = Form()
    ):
        # Manually instantiate an `OAuth2PasswordRequestForm` with their values
        credentials = OAuth2PasswordRequestForm(email=email, password=password)
        user = await user_db.authenticate(credentials)

        if user is None or not user.is_active:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=ErrorCode.LOGIN_BAD_CREDENTIALS,
            )

        return await backend.get_login_response(user, response)

    if backend.logout:

        @router.post("/logout")
        async def logout(
            response: Response, user=Depends(authenticator.get_current_active_user)
        ):
            return await backend.get_logout_response(user, response)

    return router
```

Then, you'll have to call this custom method instead of the one provided:

```py
# Before
auth_router = fastapi_users.get_auth_router(jwt_authentication)

# After
auth_router = get_auth_router(jwt_authentication, user_db, fastapi_users.authenticator)
```

Note that you'll loose the Swagger authentication integration by doing this.

Hope it helps 👍

**Comment by diflores** [comment]
Amazing! Thanks for your detailed answer. Will try to implement this! Thanks again!

**Comment by FinemechanicPub** [comment]
> Well the issue with this is that it internally uses the [OAuth2 flow provided by FastAPI](https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/#get-the-username-and-password) with the [OAuth2PasswordRequestForm class](https://github.com/tiangolo/fastapi/blob/master/fastapi/security/oauth2.py#L13)

But why is that so? Is the OAuth2PasswordRequestForm sent somewhere outside? I tried to track it and it looks like the form is passed to **user_manager.authenticate** where it is torn down to username and password.

The problem with this form is that Swagger shows login endpoint form with extra fields (grant_type, scope, client_id and client_secret) and it looks untidy.

**Comment by frankie567** [comment]
It comes from the OpenAPI specification, which only supports a few security schemes: https://swagger.io/docs/specification/authentication/ Using Using the OAuth2 Password flow is the only way of getting username/password fields into Swagger.
