### ISSUE TITLE
Permissions and Modules

### ISSUE THREAD

**Issue by lowercase00** [frankie567/fastapi-users#286]
Hey, thanks a lot for the program, seems great indeed.
I was wondering if there's any plan to add Permissions (can_list, can_edit etc) and Modules (moduleA, moduleB) to the roadmap. I would imagine being able to register the application's modules, and while registering the user being able assign permission to modules (if I'm not mistaken Flask App Builder does something similar). Probably could be used with a decorator on the routes that would check if the user has the necessary permission to access that particular module. Dependencies would be another option, albeit I don't really like those huge parameter lines being passed to the route function, but that's just me. Anyways, just an idea.
Thanks a lot!

**Comment by frankie567** [comment]
Hi @lowercase00!

Currently, this is not on the roadmap. I feel this is not in the scope of this project (see https://github.com/frankie567/fastapi-users/issues/217#issuecomment-644100504).

Cheers!
