### ISSUE TITLE
Websocket support?

### ISSUE THREAD

**Issue by SelfhostedPro** [frankie567/fastapi-users#295]
Hey, is there a way to have websocket support with this or is there a function we can call inside of a function/route to get the current user? I'm trying to use it in a function for a websocket to see if there's a user returned by get_active_user but it gives me an exception everytime:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 154, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/fastapi/applications.py", line 180, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/starlette/routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/starlette/routing.py", line 57, in app
    await func(session)
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/fastapi/routing.py", line 242, in app
    await dependant.call(**values)
  File "./backend/api/routers/apps.py", line 57, in ws
    user = await get_active_user()
  File "<makefun-gen-4>", line 2, in get_current_active_user
  File "/home/user/dev/Yacht-work/Yacht/backend/venv/lib/python3.8/site-packages/fastapi_users/authentication/__init__.py", line 96, in get_current_active_user
    raise self._get_credentials_exception()
fastapi.exceptions.HTTPException
```

**Comment by frankie567** [comment]
Well, I've not really thought about WebSockets before. Apparently, you can use `Depends` in the websocket parameters (https://fastapi.tiangolo.com/advanced/websockets/#using-depends-and-others) so I guess you can try to do `users=Depends(get_current_active_user))` ; but there will be probably some gotchas there.

**Comment by SelfhostedPro** [comment]
Yeah, I didn't have luck with this. Trying to protect a websocket that shows logs for docker containers so locking it down is important. Is there anything I can do to help this get implemented?

-------- Original Message --------

**Comment by SelfhostedPro** [comment]
Alright, I can get the jwt token as a string in websocket._cookies['fastapiusersauth'] but jwt.decode gives me `jose.exceptions.JWTClaimsError: Invalid audience`.

Is there another way I should be decoding it?

Here is an example of how it's stored in websocket._cookies['fastapiusersauth']:
```
'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiZGUwYzc0ZTItYWFjMS00ZTg4LWEwYmYtYzI0MjI4MjI2YTVjIiwiYXVkIjoiZmFzdGFwaS11c2VyczphdXRoIiwiZXhwIjoxNTk3MzM1NjI5fQ.UhO18HxDgFUDsgQ9rAbQi-W9dmWZ0XOtHTxQO74NJDM'
```
Here are my functions so far:
routers/apps.py
```
async def ws(websocket: WebSocket, app_name: str):
    cookie = websocket._cookies['fastapiusersauth']
    await websocket_auth(websocket= websocket, cookie=cookie)

```
utils.py (WiP)
```
async def websocket_auth(
    websocket: WebSocket,
    cookie: Optional[str]
):
    session = jwt.decode(cookie, settings.SECRET_KEY)
    if session is None:
        await websocket.close(code=status.WS_1008_POLICY_VIOLATION)
    return cookie
```

**Comment by SelfhostedPro** [comment]
This works:
utils.py
```py
async def websocket_auth(
    websocket: WebSocket
):
    try:
        cookie = websocket._cookies['fastapiusersauth']
        session = jwt.decode(cookie, settings.SECRET_KEY, audience='fastapi-users:auth')
    except:
        return None
    if session is None:
        return None
    return cookie
```
routers/apps.py
```py
@router.websocket("/{app_name}/livelogs")
async def ws(websocket: WebSocket, app_name: str):

    auth_success = await websocket_auth(websocket= websocket)
    if auth_success:
        await websocket.accept()
        async with aiodocker.Docker() as docker:
            container: DockerContainer = await docker.containers.get(app_name)
            logs = container.log(stdout=True, stderr=True, follow=True)
            async for line in logs:
                await websocket.send_text(line)
    else:
        await websocket.close(code=status.WS_1008_POLICY_VIOLATION)
```

Could you double check and make sure it looks alright? Might consider adding something similar to documentation for other people doing the same thing.

**Comment by frankie567** [comment]
Actually, you could reuse the `CookieAuthentication` class logic. It has a `__call__` method which expects two parameters : credentials (`str`) and a database adapter:

https://github.com/frankie567/fastapi-users/blob/9e499791deae8d7c4c25f0ef6a786f493768fff0/fastapi_users/authentication/cookie.py#L61-L63

So you can do something like this, by reusing the components of `fastapi-users`:

```py
async def websocket_auth(websocket: WebSocket):
    try:
        cookie = websocket._cookies['fastapiusersauth']
        user = await cookie_authentication(cookie, user_db)
        # User is authenticated, you can also check if he is active
        if user and user.is_active:
            return user  # You get a valid user or None

        # The credentials are invalid, expired, or the user does not exist or inactive
        return None
```

This way, you ensure the user does exist in database and `is_active`. Besides, you have the user object in your function, so you can do useful things like ensuring he is asking for his own data.

**Comment by SelfhostedPro** [comment]
Awesome! Just set this up and it works like a charm. Thanks for all of your help! This has been the most instrumental addition FastAPI for my app. I really appreciate all the work you've done!

**Comment by frankie567** [comment]
Glad to hear it, thanks 👍

**Comment by lgblkb369** [comment]
Hi guys! having troubles implementing websocket authentication. What is the currently recommended way to do this? Some example would be nice.

**Comment by peter65374** [comment]
> 



> Actually, you could reuse the `CookieAuthentication` class logic. It has a `__call__` method which expects two parameters : credentials (`str`) and a database adapter:
> 
> https://github.com/frankie567/fastapi-users/blob/9e499791deae8d7c4c25f0ef6a786f493768fff0/fastapi_users/authentication/cookie.py#L61-L63
> 
> So you can do something like this, by reusing the components of `fastapi-users`:
> 
> ```python
> async def websocket_auth(websocket: WebSocket):
>     try:
>         cookie = websocket._cookies['fastapiusersauth']
>         user = await cookie_authentication(cookie, user_db)
>         # User is authenticated, you can also check if he is active
>         if user and user.is_active:
>             return user
> 
>         # The credentials are invalid, expired, or the user does not exist or inactive
>         return None
> ```
> 
> This way, you ensure the user does exist in database and `is_active`. Besides, you have the user object in your function, so you can do useful things like ensuring he is asking for his own data.

Really instructive and useful. It seems that we could reuse JWTAuthentication class to handle Websocket endpoint path token in similar way. Thank you.

**Comment by sorXCode** [comment]
> Hi guys! having troubles implementing websocket authentication. What is the currently recommended way to do this?

This works for me.

```python3
async def get_user_from_cookie(websocket: WebSocket, user_manager = Depends(get_user_manager)):
    cookie = websocket.cookies.get("fastapiusersauth")
    user = await cookie_auth_backend.get_strategy().read_token(cookie, user_manager)
    if user and user.is_active:
        yield user
    raise WebSocketException("Invalid user")


@router.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket, user: User = Depends(get_user_from_cookie)):
    # you can use the user in the function e.g print the user
    print("user ->", user)
```

**Comment by sorXCode** [comment]
> Hi guys! having troubles implementing websocket authentication. What is the currently recommended way to do this?

This works for me.

```python3
async def get_user_from_cookie(websocket: WebSocket, user_manager = Depends(get_user_manager)):
    cookie = websocket.cookies.get("fastapiusersauth")
    user = await cookie_auth_backend.get_strategy().read_token(cookie, user_manager)
    if not user or not user.is_active:
        raise WebSocketException("Invalid user")
    yield user

@router.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket, user: User = Depends(get_user_from_cookie)):
    # you can use the user in the function e.g print the user
    print("user ->", user)
```
