### ISSUE TITLE
Weird response from /auth/register

### ISSUE THREAD

**Issue by Houjio** [frankie567/fastapi-users#302]
When making a request to /auth/register through curl or python requests I have no problem registering a user. When I run it through Jquery Ajax I get back the error message:

> Expecting value: line 1 column 1 (char 0)

I looked through some of the code to find out why I would get this back without results.

Here is my Ajax call:

`$.ajax({`
                `    "url": "/auth/register",`
              `      "method": "post",`
                `    "headers": {`
                `        "accept": "application/json",`
                 `       "Content-Type": "application/json"`
          `          },`
               `     "data": {`
                   `     "email": 'testpassword12@gmail.com',`
                  `      "password": 'somestring',`
                 `   },`
               `     success: function(resp) {`
   `                     console.log(resp);`
      `              },`
                `    error: function(err) {`
               `         console.log(err);`
          `          }`
            `    });`

I didn't have any issues with login and ajax. How can I fix this, and is there a way to make it more obvious how to fix it if someone gets this issue too?

**Comment by frankie567** [comment]
It's been a while since I've used jQuery, but my guess is that you have to `JSON.stringify` your data before sending it. You should also set `dataType: "json"` to help jQuery parse the response correctly:

```js
$.ajax({
  "url": "/auth/register",
  "method": "post",
  "headers": {
    "accept": "application/json",
    "Content-Type": "application/json"
  },
  "dataType": "json",
  "data": JSON.stringify({
    "email": 'testpassword12@gmail.com',
    "password": 'somestring',
  }),
  success: function(resp) {
    console.log(resp);
  },
  error: function(err) {
    console.log(err);
  }
});
```

**Comment by frankie567** [comment]
As a side note, I strongly recommend, if you can, to switch to a more modern HTTP request library like [`axios`](https://github.com/axios/axios).
