### ISSUE TITLE
Cannot register due to Pydantic Validation Error

### ISSUE THREAD

**Issue by Boot-Error** [frankie567/fastapi-users#320]
I want to integrate fastapi-users into my application and while following the tutorial of using FastAPI users with
- db as mongodb
- jwt token authentication

I receive this internal server error at `/auth/register`, the trace has the line few lines denoting validation error by pydantic.
```
  File "/home/booterror/Development/Contributing/tsaasg/hwb_fastapi/venv/lib/python3.8/site-packages/fastapi_users/router/register.py", line 35, in register
    db_user = user_db_model(
  File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for UserDB
id
  field required (type=value_error.missing)
```

At registration shouldn't the `id` be generated?

**Comment by Boot-Error** [comment]
This happens only when I try to add additional Parameters to `User` class.

**Comment by Boot-Error** [comment]
Okay I figured it out, guess this wasn't mentioned in the documentation.

# if you are adding additional parameters to your User Model then
- Add the parameters in Optional in the User Model
- Add the parameters in UserCreate Model

Example:
```python
class User(models.BaseUser):
    birthdate: Optional[str]

class UserCreate(models.BaseUserCreate):
    birthdate: str
```

This solves issues I found at 
1. `/register` router where there was a validation error
2. `/auth/jwt/login` when authentication, if the parameters aren't in Optional, it would throw validation error regarding missing value. Thanks to this statement in the [FastAPI users usage flow documentation](https://frankie567.github.io/fastapi-users/usage/flow/#response)

Hope this help, closing the issue!

**Comment by frankie567** [comment]
Also maybe check my answer in issue #318:

> Your UserDB class should inherit from the User class:
> 
> ```py
> class UserDB(User, models.BaseUserDB):
>     pass
> ```
