### ISSUE TITLE
Pydantic validation error with OAuth / SQLAlchemy

### ISSUE THREAD

**Issue by tomlew-ceva** [frankie567/fastapi-users#325]
First of all thanks a lot for the fastapi-users work, it is a wonderful initiative that helps a lot!!
Using it with SQLAlchemy and both cookie and google oath, I have had an issue with pydantic validation inside the make_user function, and I may have a lead to solve it.

More precisely, when calling "get_by_email" on an existing user that has already logged in with Google Auth, I get the following error:

>   File "fastapi_users/db/sqlalchemy.py", line 127, in get_by_email
>     return await self._make_user(user) if user else None
>   File "fastapi_users/db/sqlalchemy.py", line 201, in _make_user
>     return self.user_db_model(**user_dict)
>   File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 5 validation errors for UserDB
> oauth_accounts -> 0 -> oauth_name
>   field required (type=value_error.missing)
> oauth_accounts -> 0 -> access_token
>   field required (type=value_error.missing)
> oauth_accounts -> 0 -> expires_at
>   field required (type=value_error.missing)
> oauth_accounts -> 0 -> account_id
>   field required (type=value_error.missing)
> oauth_accounts -> 0 -> account_email
>   field required (type=value_error.missing)
> 

I believe the root cause is that the field "oauth_accounts" is directly copied by (lines 198-199):
```
            oauth_accounts = await self.database.fetch_all(query)
            user_dict["oauth_accounts"] = oauth_accounts
```
which returns a list of database Records rather than a dictionary.
```
            oauth_accounts = await self.database.fetch_all(query)
            user_dict["oauth_accounts"] = [{**account} for account in oauth_accounts]
```

Would that look as a good solution?

Thanks again for your work!!

**Comment by frankie567** [comment]
Hi @tomlew-ceva!

Thank you for your bug report. Unfortunately, I can't find a way to reproduce it in unit tests. Actually, there is a unit test that ensures it's working: https://github.com/frankie567/fastapi-users/blob/c5f53b73d1fd665a6c2850ab3bce7f2d02f0f5b4/tests/test_db_sqlalchemy.py#L155-L201

When I dig into this, the `oauth_accounts` results from SQLAlchemy is a list of [`RowProxy`](https://docs.sqlalchemy.org/en/13/core/connections.html#sqlalchemy.engine.RowProxy), which should behave as a dictionary.

Could you check into your database that the `oauth_account` is correctly created and that the row for your user is correctly filled?

**Comment by aceSkotheim** [comment]
Hi @frankie567 and @tomlew-ceva,
Just getting this working and it looks like it will fit my purposes perfectly! Truly appreciate the work you are doing, please keep it up!
I ran into the exact problem that @tomlew-ceva had and his solution worked. Prior to implementing the solution, I did the unit-tests and it pass all tests. I noticed that it would work as expected on the first time logging in, but then fail with the error above when you tried to log in again.
Again, thanks for all your work!
Jason
