### ISSUE TITLE
Can't add fields for register model

### ISSUE THREAD

**Issue by lvar** [frankie567/fastapi-users#329]
I'm trying to add some extra fields for register users, here is my code:

`

      from tortoise import fields
      from tortoise.contrib.pydantic import pydantic_model_creator
      from fastapi_users import models
      from fastapi_users.db import TortoiseBaseUserModel, TortoiseUserDatabase
      from tortoise.contrib.starlette import register_tortoise

      class User(models.BaseUser):
         nombre = fields.CharField(max_length=100)
         apellidos = fields.CharField(max_length=100)
    

      class UserCreate(models.BaseUserCreate):
          pass

     class UserUpdate(User, models.BaseUserUpdate):
          pass

     class UserDB(User, models.BaseUserDB):
          pass

     class UserModel(TortoiseBaseUserModel):
          pass

      user_db = TortoiseUserDatabase(UserDB, UserModel)`

but getting this error, don't know why...please help!:

_**RuntimeError: no validator found for <class 'tortoise.fields.data.CharField'>, see `arbitrary_types_allowed` in Config**_

**Comment by frankie567** [comment]
You are confusing Tortoise fields and Pydantic fields. You should add your fields in the Pydantic models (which are used by FastAPI for API validation), and in the Tortoise model (which is used for database management). Something like this:

```py
# Pydantic models
class User(models.BaseUser):
    nombre: str
    apellidos: str

class UserCreate(models.BaseUserCreate):
    pass

class UserUpdate(User, models.BaseUserUpdate):
    pass

class UserDB(User, models.BaseUserDB):
    pass

# Tortoise model
class UserModel(TortoiseBaseUserModel):
    nombre = fields.CharField(max_length=100)
    apellidos = fields.CharField(max_length=100)
```

**Comment by lvar** [comment]
@frankie567 Working!! I'm a fool hahaha Thank you!!
