### ISSUE TITLE
Additional unique fields

### ISSUE THREAD

**Issue by kellen** [frankie567/fastapi-users#332]
I added a unique screen name field to the user model:

```
class UserCreate(fastapi_users.models.BaseUserCreate):
    display_name: str

class UserDB(models.User, fastapi_users.models.BaseUserDB):
    display_name: str


class UserTable(Base, SQLAlchemyBaseUserTable):
    display_name = Column(String, nullable=False, unique=True)
```

But I'm not seeing anywhere to hook in to the register route & verify that a submitted name is unique before creation is attempted which results in a DB error when the uniqueness constraint is violated.

I can hack around this by copypasting the route but some api for validation in such cases would be better.

**Comment by frankie567** [comment]
Well, the issue in this case is that we have to do a database query to ensure the `display_name` is unique ; contrary to "simple" validation that could occur in the Pydantic model.

Currently, there is no way to hook directly into the route. I believe what you could do instead of copy/pasting the route is to implement your custom route and call the provided route after if your validation passes. Something like (not tested):

``` py
register_router = fastapi_users.get_register_router(on_after_register)
custom_register_router = APIRouter()


@custom_register_router.post(
    "/register", response_model=User, status_code=status.HTTP_201_CREATED
)
async def register(request: Request, user: UserCreate):
    existing_user = await get_user_by_display_name(user.display_name)
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=ErrorCode.REGISTER_USER_ALREADY_EXISTS,
        )

    return register_router.routes[0].endpoint(request, user)

```

**Comment by kellen** [comment]
Ah, that's not a terrible solution, thanks. Perhaps worth adding to the docs.

**Comment by Glitchy-Sheep** [comment]
Hello, the solution proposed above seems to be no longer very relevant, but I found a great way to override the behavior of the router, the secret is that we don’t even need it, just override the create method in the **user manager**!

That is, we can wedge ourselves into the user creation process at a slightly later stage:

```python
# Same manager which we already use
class UserManager(UUIDIDMixin, BaseUserManager[User, uuid.UUID]):
    reset_password_token_secret = SECRET
    verification_token_secret = SECRET

    # Override create, injecting some check logic and then call Parent function via super()
    async def create(
        self,
        user_create: UserCreate,  # ancestor of the Base schema so it's ok
        safe: bool = False,
        request: Optional[Request] = None,
    ) -> models.UP:

        # >>>>>>>> Any check logic here >>>>>>>>>>>
        existing_user = await UsersDAO.get_user_by_username(user_create.username)
        if existing_user:
            # HTTPException is an ancestor of the Exception so it's ok too
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=ErrorCode.REGISTER_USER_ALREADY_EXISTS,
            )
        # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        return await super().create(user_create, safe, request)
```

So in this case we need even less code.
I don't know if it's the best solution, but it works great for me.

P.S: It's a pretty common use case to add usernames, maybe we should mention this in the docs?
@frankie567
