### ISSUE TITLE
Is there a on_after_reset_password hook when calling /auth/reset-password successfully?

### ISSUE THREAD

**Issue by p3t3r67x0** [frankie567/fastapi-users#335]
Hi great tool, thumbs up! 

I wonder if there is something like a `on_after_reset_password` hook when calling /auth/reset-password successfully?

What I have so far looks like this but I could not figure out if there is a callback `on_after_reset_password`.

```python
app.include_router(
    fastapi_users.get_reset_password_router(
        SECRET,
        after_forgot_password=on_after_forgot_password,
        reset_password_token_lifetime_seconds=3600
    ),
    prefix='/auth',
    tags=['auth'],
)
```

Do I miss anything?

**Comment by frankie567** [comment]
Hi there!

Unfortunately, no, there is no `on_after_reset_password` hook at the moment. What would you be your use-case for this?

Cheers!

**Comment by p3t3r67x0** [comment]
Hi thanks for your quick response. Really appreciate your work! The use case would be to send the user an email that the password was changed and if it wasn't the user he might has to contact the support. Did you got what I mean?

**Comment by frankie567** [comment]
Yes, I totally get it! Unfortunately, there is no way to do this at the moment ; but I'll definitely think about it!

**Comment by frankie567** [comment]
Implementation done and merged! Will be released soon 👍

**Comment by frankie567** [comment]
@all-contributors add @p3t3r67x0 for ideas
