### ISSUE TITLE
VARCHAR requires a length on dialect mysql

### ISSUE THREAD

**Issue by lill74** [frankie567/fastapi-users#343]
Hello
# Problem
There is something error on creating tables on MySQL.
`
sqlalchemy.exc.CompileError: (in table 'user', column 'email'): VARCHAR requires a length on dialect mysql
`
effected columns
SQLAlchemyBaseUserTable:
email
hashed_password

SQLAlchemyBaseOAuthAccountTable:
oauth_name
access_token
refresh_token
account_id
account_email

https://github.com/frankie567/fastapi-users/blob/0134a43fade100c32588a0bf09d21b1939d24c8e/fastapi_users/db/sqlalchemy.py#L56

According to SQLAlchemy Docs, 
`CREATE TABLE DDL is issued if a VARCHAR with no length is included.`

# Solution
Pull request #344

**Comment by lill74** [comment]
I think the best way of solve this problem is adding length to columns.

**Comment by nicolaipre** [comment]
I am experiencing the same problem.
