### ISSUE TITLE
Frontend Auth Form

### ISSUE THREAD

**Issue by hannawagner** [frankie567/fastapi-users#367]
Hello!
I've tried making a simple register/login form with FastAPI but I failed. My idea was to send a simple json object containing username and password using pythons request.  I get the email and password from a simple HTML form and then post it to "auth/register".
```
<form action="/auth/register-user" enctype="multipart/form-data"
          method="post">
        Email: <input name="email" type="text" >
        Password: <input name="password" type="text" >
        <input type="submit">
 </form>
```
```
@app.post("/auth/register-user")
def register_user(email: str = Form(...), password: str = Form(...)):
    r = requests.post("http://localhost:5000/auth/register",
                      data={'email': email, 'password': password})
```

Could somebody please tell me what kind of data/format I should send to the "auth/register"?

**Comment by frankie567** [comment]
Hi there!

Similar question in #188:

>FastAPI is intended to be used as a REST API, not a traditional web framework like Django that generates HTML response.
>
> The correct way to do this is to write a bit of JavaScript in your page to handle the form submission, handle the response and make the redirection.

So you shouldn't write this in Python, but rather in JavaScript along with your HTML. You should read about AJAX requests : https://www.w3schools.com/xml/ajax_intro.asp

**Comment by UnoYakshi** [comment]
@frankie567, there is really no way register/login/etc. w/o AJAX?..

My situation: we have an SPA front-end for regular users and an HTML-based responses for those who don't want to use JS (say, for security-anonymity reasons). For simplicity, I use cookie-based JWT from FastAPI-Users for now.

**Comment by UnoYakshi** [comment]
Nevermind, it works via an async proxy route. For those, who'll be looking for the answer:

```html
    <form method="post" id="auth_form">
        <label for="email">E-mail:</label><br>
        <input type="text" id="email" name="email">

        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password">

        {# Login button... #}
        <input class="submit bg-info text-light" type="submit" formaction="{{ url_for('register_proxy_proxy') }}" value="Login">

        {# Register button... #}
        <input class="submit" type="submit" formaction="{{ url_for('register_proxy') }}" value="Sign Up">

        {# Forgor password button... #}
        <br>
        <input class="submit" type="submit" formaction="{{ url_for('forgot_password_proxy') }}" value="Remind password">
    </form>
```

```python3
@app.post('/register_proxy')
async def register_proxy(email: Annotated[str, Form()], password: Annotated[str, Form()]) -> dict[str, str]:
    """Registration proxy for HTML sign-up form..."""

    import httpx

    async with httpx.AsyncClient() as client:
        response = await client.post(url='http://localhost:8000/auth/register', json={'email': email, 'password': password})
    return {'response': response.text}
```

Keep in mind that `-> Response` gives me `ValueError: [TypeError("'TimerHandle' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]`, however, the user is still created in the database.

**Comment by talhaanwarch** [comment]
@UnoYakshi just checking did you open-source your code ?

**Comment by UnoYakshi** [comment]
> @UnoYakshi just checking did you open-source your code ?

What code exactly are we talking about?
All the code for the project I was working on that time is [here](https://github.com/UnoYakshi/FRAAND).
