### ISSUE TITLE
Create Superuser on startup

### ISSUE THREAD

**Issue by akshatcx** [frankie567/fastapi-users#375]
Hi,

Really appreciate the work you have done here.

I was wondering is there a way to add a default superuser using startup itself?
I tried manually adding it to the db (mongo) but it gives me 401 when trying to access any route.

```
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

superuser = {
        "id": uuid4(),
        "email": os.getenv("SUPERUSER_EMAIL"),
        "hashed_password": pwd_context.hash(os.getenv("SUPERUSER_EMAIL")),
        "is_active": True,
        "is_superuser": True
    }
    await db["users"].insert_one(superuser)

**Comment by frankie567** [comment]
I usually advise against creating a superuser on startup.

What I recommend is to register a user using the API, and then put the `is_superuser` flag to `True` for that user in the database. It only takes a minute to do.

**Comment by akshatcx** [comment]
Thank you so much for the prompt response frankie! :))

I understand that but I want to automate the entire process so that there is no dependency for other people when building this application for development. 

Moreover, this will also help with the tests as I will have a default super-user which I can use in the tests. (pytest)

Maybe there is an alternative that I can use (like a cli or something) to automatically create a super-user when the tests are run.

**Comment by frankie567** [comment]
After thinking about this, it would be nice to have a function that handle user creation, instead of having the logic nested in the route. This way, developers could import it where they want and use it programmatically. I'll work on this.

**Comment by frankie567** [comment]
I'll close this issue in favor of #391.

**Comment by akshatcx** [comment]
Thank you so much for the consideration :))
