### ISSUE TITLE
How to extend the User

### ISSUE THREAD

**Issue by kstadler** [frankie567/fastapi-users#380]
It would be great if there was a tutorial on how to extend the User by custom fields.
E.g. I'd like to add an username field.
I tried the following in my main.py:
```
class User(models.BaseUser):
    username: str


class UserCreate(models.BaseUserCreate):
    username: str


class UserUpdate(User, models.BaseUserUpdate):
    username: str


class UserDB(User, models.BaseUserDB):
    username: str

....

class UserTable(Base, SQLAlchemyBaseUserTable):
    username = Column(String(length=32), nullable=False)
```
But all I get on registering a new user is an interal server error. Not even anything in the logs. Why is that so?

**Comment by kstadler** [comment]
Update: Seems I needed to reset my sqlite database, now everything ist working.
Though I still wonder why there was no error message in my logs.

**Comment by frankie567** [comment]
Hi there,

Sorry for the delayed response! Indeed, when changing the structure of your entities, you need to update the structure of your SQL database. You can either do this by hand or implement migrations (e.g. with [Alembic](https://alembic.sqlalchemy.org/en/latest/)).

The lack of error message is strange indeed ; if you get a 500 error, you should have a stacktrace in the server console.
