### ISSUE TITLE
Pony orm support

### ISSUE THREAD

**Issue by lvar** [frankie567/fastapi-users#384]
Would be great if you can add support for pony orm

https://ponyorm.org/

**Comment by frankie567** [comment]
Hi there!

Sorry for the delayed response; PonyORM seems nice but from what I see it doesn't support asyncio. With FastAPI, I tend to favor async connectors, as it's the real selling point of the framework with improved performance and all.

That said, it should be fairly easy to implement a database adapter yourself. You can get inspiration from the Tortoise ORM one : https://github.com/frankie567/fastapi-users/blob/master/fastapi_users/db/tortoise.py
