### ISSUE TITLE
Wrong credentials type in routers.auth module

### ISSUE THREAD

**Issue by izdwuut** [frankie567/fastapi-users#387]
Hi!

Thanks for writing this utility. It saved me tremendous amount of work. Keep up the good work!

I noticed a thing. In `get_auth_router` method from `routers.auth` module, `credentials` argument is of `OAuth2PasswordRequestForm` type. Because of that, the following fields can be provided in a `/login` request:

```
grant_type
username
password
scope
client_id
client_secret
```

From what I understand, only these fields should be accepted:

```
username
password
```

I believe that another type should be used. I've been thinking of `fastapi.security.HTTPBasicCredentials`. It comes only with the fields needed. It would modify the current payload type, which is `application/x-www-form-urlencoded` .

**Comment by frankie567** [comment]
Hello there!

Sorry for the delayed response. Actually, I followed what is recommended in the FastAPI documentation and official starters : https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/ It may sound weird, but it worked quite nicely until now.

`fastapi.security.HTTPBasicCredentials` would not work in our case, as it refers to the HTTP Basic Auth scheme, with credentials set in headers : https://fastapi.tiangolo.com/advanced/security/http-basic-auth/?h=+httpbasi#simple-http-basic-auth

**Comment by izdwuut** [comment]
I see. Anyways, I guess I was wrong. According to OAuth2 framework [RFC](https://tools.ietf.org/html/rfc6749#section-4.3.2), you are required to send parameters defined by `OAuth2PasswordRequestForm` form. I wasn't aware of that.
