### ISSUE TITLE
Put user creation logic in a importable function

### ISSUE THREAD

**Issue by frankie567** [frankie567/fastapi-users#391]
Following discussion in #375, I think it would be nice to have a user creation function with all the related logic instead of having it nested in register route.

**Comment by frankie567** [comment]
Released in [3.1.0](https://github.com/frankie567/fastapi-users/releases/tag/v3.1.0).

**Comment by akshatcx** [comment]
Thank you so much for this :)

**Comment by kamikaze** [comment]
in 8.x.x it seems very cryptic how to achieve this in code. Still can't figure out
