### ISSUE TITLE
Tortoise-orm custom user

### ISSUE THREAD

**Issue by ScrimForever** [frankie567/fastapi-users#392]
Iḿ trying make custom user with fastapi_users,

so 

from fastapi_users import models
from fastapi_users.db import TortoiseBaseUserModel, TortoiseUserDatabase
import datetime

class User(models.BaseUser):

    nome: str = "defaultuserteste"
    data_criado: str = datetime.datetime.now()
    is_fund: bool = False
    is_agendador: bool = False
    is_revisor: bool = False
    is_aprovador: bool = False

class UserCreate(models.BaseUserCreate):

    nome: str = "defaultuserteste"
    data_criado: str = datetime.datetime.now()
    is_fund: bool = False
    is_agendador: bool = False
    is_revisor: bool = False
    is_aprovador: bool = False

class UserUpdate(User, models.BaseUserUpdate):

    nome: str = "defaultuserteste"
    data_criado: str = datetime.datetime.now()
    is_fund: bool = False
    is_agendador: bool = False
    is_revisor: bool = False
    is_aprovador: bool = False

class UserDB(User, models.BaseUserDB):

    nome: str = "defaultuserteste"
    data_criado: str = datetime.datetime.now()
    is_fund: bool = False
    is_agendador: bool = False
    is_revisor: bool = False
    is_aprovador: bool = False

class UserModel(TortoiseBaseUserModel):

    nome: str = "defaultuserteste"
    data_criado: str = datetime.datetime.now()
    is_fund: bool = False
    is_agendador: bool = False
    is_revisor: bool = False
    is_aprovador: bool = False

user_db = TortoiseUserDatabase(UserDB, UserModel)

Database not changed i'm using mysql ... nothings happening.

**Comment by frankie567** [comment]
Did you manage your SQL migrations so that the database structure is updated : https://tortoise-orm.readthedocs.io/en/latest/migration.html ?

**Comment by ScrimForever** [comment]
Yes. But when i show columns inside table, not created then...
I init , init-db, but table not apply new fields

**Comment by frankie567** [comment]
I've updated the Tortoise ORM examples, so it should work out-of-the-box. Take care however of the path of your models module: 

```py
register_tortoise(
    app,
    db_url=DATABASE_URL,
    modules={"models": ["path_to_your_package"]},  # <<< 🔴 It should be the dotted path of your Python module containing the models
    generate_schemas=True,  # Please also read : https://tortoise-orm.readthedocs.io/en/latest/setup.html?highlight=generate_schemas#tortoise.Tortoise.generate_schemas
)
```

* https://frankie567.github.io/fastapi-users/configuration/databases/tortoise/
* https://frankie567.github.io/fastapi-users/configuration/full_example/#tortoise-orm

However, I still **strongly** recommend to look into a migration system so that schema creation and update is handled properly : https://tortoise-orm.readthedocs.io/en/latest/migration.html

**Comment by ScrimForever** [comment]
@frankie567 

I use exactly as you inform, but my models usuarios, not migration. All others models i can use, all my custom models, just usermodel not create. How can i give more information ?

**Comment by frankie567** [comment]
Could you show us your `register_tortoise` function call?

**Comment by ScrimForever** [comment]
TORTOISE_ORM = {
    "connections": {"default": "mysql://xxxx:xxxx@xxx.xxx.xxx.xxx:3306/fund_api"},
    "apps": {
        "models": {
            "models": ["models", "aerich.models"],
            "default_connection": "default",
        },
    },
}

register_tortoise(
    app,
    #db_url="sqlite://db.sqlite"
    #db_url="mysql://xxxxxx:xxxxxxx@xxx.xxx.xxx.xxx:3306/fund_api",
    modules={"models": ["models"]},
    generate_schemas=True,
    add_exception_handlers=True,
    config=TORTOISE_ORM,
)

**Comment by ScrimForever** [comment]
#Update

The table has been created, so the "columns" that informed on Classes, like:
nome: str = "defaultuserteste"
data_criado: str = datetime.datetime.now()
is_fund: bool = False
is_agendador: bool = False
is_revisor: bool = False
is_aprovador: bool = False

not created.

The table created has name usermodel, with columns (id, email, hashed_password, is_active, is_superuser)

**Comment by frankie567** [comment]
OK, I see what happens ; I didn't notice it in your first message. In your Tortoise model, you wrote this:

```py
class UserModel(TortoiseBaseUserModel):
    nome: str = "defaultuserteste"
    data_criado: str = datetime.datetime.now()
    is_fund: bool = False
    is_agendador: bool = False
    is_revisor: bool = False
    is_aprovador: bool = False
```

This is wrong. Field definitions in Tortoise are not the same as in Pydantic. You should follow the Tortoise way of definining fields. Something like:

```py
class UserModel(TortoiseBaseUserModel):
    nome = fields.CharField(max_length=255)
    data_criado = fields.DatetimeField()  
    is_fund = fields.BooleanField()
    # ...
```

Be sure to check the getting started document of Tortoise: https://tortoise-orm.readthedocs.io/en/latest/getting_started.html

**Comment by ScrimForever** [comment]
@frankie567 .

So sorry, i wrote wrong really. So, i did it as tortoise example, and columns not created too. 

If i edit directly on module fastapi-users on class BaseUser(CreateUpdateDictModel):
its works.

**Comment by ScrimForever** [comment]
Finally works.
The problem was i not set variable in alls classes and on UserModel i needed add class Config: with orm_mode = True.

Resolved !
