### ISSUE TITLE
Tortoise ORM not updating database

### ISSUE THREAD

**Issue by eddsalkield** [frankie567/fastapi-users#393]
Currently, the [full example](https://frankie567.github.io/fastapi-users/configuration/databases/tortoise/#register-tortoise) for Tortoise ORM is failing.

When the server is started, the database models aren't written to the sqlite file, `test.db`.  When the `/auth/register` route is called, the server fails with `tortoise.exceptions.OperationalError: no such table: usermodel`.

This may be related to #392.

**Comment by ScrimForever** [comment]
@eddsalkield , did you know some workaround to make this stable while is there no solution ?

**Comment by frankie567** [comment]
I've updated the Tortoise ORM examples, so it should work out-of-the-box. Take care however of the path of your models module: 

```py
register_tortoise(
    app,
    db_url=DATABASE_URL,
    modules={"models": ["path_to_your_package"]},  # <<< 🔴 It should be the dotted path of your Python module containing the models
    generate_schemas=True,  # Please also read : https://tortoise-orm.readthedocs.io/en/latest/setup.html?highlight=generate_schemas#tortoise.Tortoise.generate_schemas
)
```

* https://frankie567.github.io/fastapi-users/configuration/databases/tortoise/
* https://frankie567.github.io/fastapi-users/configuration/full_example/#tortoise-orm

However, I still **strongly** recommend to look into a migration system so that schema creation and update is handled properly : https://tortoise-orm.readthedocs.io/en/latest/migration.html

**Comment by eddsalkield** [comment]
Thanks so much, I was missing the `generate_schemas` key.

**Comment by ScrimForever** [comment]
@eddsalkield , 

I used generate_schemas and in mysql this not happening.

I willl show you my config 

TORTOISE_ORM = {
    "connections": {"default": "mysql://user:password@xxx.xxx.xxx.xxx:3306/fund_api"},
    "apps": {
        "models": {
            "models": ["models", "aerich.models"],
            "default_connection": "default",
        },
    },
}


register_tortoise(
    app,
    modules={"models": ["models"]},
    generate_schemas=True,
    add_exception_handlers=True,
    config=TORTOISE_ORM,
)

all others tables create normaly, just user not

**Comment by eddsalkield** [comment]
Seems like this is unrelated to the issue at hand in this thread, and is probably to do with the way you're linking the user model into the login flow provided by `fastapi-users`.

Try simplifying your code to narrow down where the problem is.  You'll know whether it's a bug in `fastapi-users` or a mistake in your code once you can precisely specify how to reproduce the issue.  If you can reproduce it in a minimal example, and conclude that this is the result of a bug, then I'd advise you update your issue #392 with your findings.  The other issue tracker is where this discussion belongs.
