### ISSUE TITLE
Empty password allowed?

### ISSUE THREAD

**Issue by titogarrido** [frankie567/fastapi-users#396]
How to prevent an register with a password or username field with less than 6 characters?

thanks!

**Comment by frankie567** [comment]
Hi there!

You can add your own password validator on the `UserCreate` class. Something like this:

```py
class UserCreate(models.BaseUserCreate):
    @validator('password')
    def valid_password(cls, v: str):
        if len(v) < 6:
            raise ValueError('Password should be at least 6 characters')
        return v
```

You can even have more complex things! Check the Pydantic validation doc to know more : https://pydantic-docs.helpmanual.io/usage/validators/

I think I will add it to the documentation, it's quite important!

Cheers!
