### ISSUE TITLE
Integration with Firebase Auth

### ISSUE THREAD

**Issue by kwatog** [frankie567/fastapi-users#397]
I'm not sure if it's documented but I can't find a sample of integration with Firebase Auth. Basically what I want is that after verifying the idToken, the api should be able to generate the JWT token. Along with it will be the creation of the user if the id does not exists yet.

Has anyone implemented something like this? I do understand that there's option to use Google oAuth but I can't wrap my head around it just yet.

**Comment by frankie567** [comment]
I don't know much about Firebast Auth, but the way I see it, it's a service that fully implements authentication logic right? So if you use it, you don't need `fastapi-users`. I may be mistaken here so correct me if I'm wrong.

**Comment by kwatog** [comment]
thanks for taking time to answer. 

I realized that **generate_jwt** inside the utils is that I need. Here's a high-level idea of what I want to do. 

**notes to those who are reading this: consider this as a pseudo code, please don't just copy-paste.**
```
@router.post("/auth/verifytoken")
async def verifytoken(id_token: str):

   #use firebase sdk to get verify and retrieve user details
   decoded_token = auth.verify_id_token(id_token)
   #extract the uid
   uid = decoded_token['uid']

   #retrieve user from DB
   user = UserDB.get({ 'uid': uid })
    #prepare input
    data = {
        "user_id": user.id, 
        "aud": jwt_authentication.token_audience 
    }
    #generate token
    token = generate_jwt(
        data, 
        jwt_authentication.lifetime_seconds, 
        jwt_authentication.secret, 
        JWT_ALGORITHM)    
   
    return {"access_token": token, "token_type": "bearer"}
```

**Comment by kirankbee** [comment]
How are you retrieving the auth token? Your code  should work after  request.response.get['id-token']. I have  the same issue
