### ISSUE TITLE
Custom Filter in Getting Mongo User Model

### ISSUE THREAD

**Issue by kwatog** [frankie567/fastapi-users#398]
Can we have another method for MongoDBUserDatabase to query by custom field. Basically, we just pass the filter. Currently, we have the get (by id), get_by_email, and get_by_oauth_account.

the use-case for this is if you have another key (e.g, firebase uid) with which you'll retrieve the user. having this will give you more flexibility. of course, one workaround is to just populate the oauth.

My current workaround is to subclass MongoDBUserDatabase and add another method as below.

```
class CustomMongoDBUserDB(MongoDBUserDatabase):
    async def get_one(self, filter) -> Optional[UD]:
        user = await self.collection.find_one(filter)
        return self.user_db_model(**user) if user else None
```
and then
```
db=client[settings.MONGO_DB]
collection = db[settings.COLLECTION_USER]

user_db = CustomMongoDBUserDB(UserDB, collection)
```

usage
```
user = await user_db.get_one({"uid": uid})
```

**Comment by frankie567** [comment]
Well, what you did here seems 100% correct and clean 🙂 I don't think it will have any benefit to add it into the library.

**Comment by kwatog** [comment]
fair enough. closing this.
