### ISSUE TITLE
Docs: correct curl command for logout 

### ISSUE THREAD

**Issue by FlorianBorn** [frankie567/fastapi-users#399]
Hey,
I think there is an error in the docs (https://frankie567.github.io/fastapi-users/usage/flow/#6-logout).
Using the given example with Cookie authentication gives an "Unauthorized" response.

```
curl \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $TOKEN" \
-X POST \
http://localhost:8000/auth/cookie/logout
```
should be changed to:
```
curl \  
-H "Content-Type: application/json" \  
-H "Cookie: fastapiusersauth=$TOKEN" \  
-X POST \  
http://localhost:8000/auth/cookie/logout  
```

**Comment by frankie567** [comment]
True! Nice catch! Would you be willing to do a PR for this? 😄
