### ISSUE TITLE
Advanced rights system

### ISSUE THREAD

**Issue by prostomarkeloff** [frankie567/fastapi-users#41]
Hello, firstly i wanna say you that this library really good and useful, thank you!
My question will be about delimitation user access to some methods.
What about rights system? Now out of the box we can use only `is_superuser` as rights check.
In future fastapi-users will support more ways to checking rights? This library looks to me really good, but however i must write custom rights system for not 1 file project. Or for more efficient should we create a new library for it?

**Comment by frankie567** [comment]
Thank you for your feedback 👍 

I understand the need, but I don't think this will fit into the library. My idea is that I want to keep it as light as possible, and very easy to extend and customize.

I took lot of inspiration from the builtin Django auth system. We can argue that Django has a [permission system based on model](https://docs.djangoproject.com/en/2.2/topics/auth/default/#permissions-and-authorization) (does a user can create/edit/delete the Posts?), but personally, I've never used it. From my experience, rights management is tightly related to the business logic and quite different from a project to another. Typically, a user can only modify the object they have created ; or a group of users have the rights on the objects other users of the group have created. All of this is quite specific and hard to make generic in a library, IMO.

**Comment by prostomarkeloff** [comment]
Thank you for answer! I hear you, now i think that it's not needed in this library, too. Your way of this library looks more good to me, Django-way is bad especially for this library.
