### ISSUE TITLE
Improve authentication

### ISSUE THREAD

**Issue by frankie567** [frankie567/fastapi-users#42]
Currently, only one authentication backend is allowed at a time. This is wrong. One could wish for example to use both Cookie and a Bearer token strategies.

Still taking inspiration from Django, the goal would be to be able to define a list of auth backends. There would be then a wrapper that would run sequentially until it finds a strategy that yield a user ; or raise 401.

Here is a non-working first attempt: 5160dba0043dadc57c36093573d44e7d852e31c7

This approach is promising but currently blocked by https://github.com/tiangolo/fastapi/issues/679.

**Comment by prostomarkeloff** [comment]
LGTM
