### ISSUE TITLE
Redirect when user is Unauthorized

### ISSUE THREAD

**Issue by hannawagner** [frankie567/fastapi-users#423]
Hello :)

I'm using fastapi-users as part of my fastapi web application. My goal is to redirect to the login page once a user is not logged in anymore!  Therefore I have it included as a router in my main.py file.
In my **main** I have following exception handler for redirecting if the user is not logged in:
```
class RequiresLoginException(Exception):
   pass

@app.exception_handler(RequiresLoginException)
async def exception_handler() -> Response:
    return RedirectResponse(url='/login-form')
   
def get_cookie_authorization(request: Request):
    """Check if user is logged in."""
    cookie_authorization: str = request.cookies.get("fastapiusersauth")
    if not cookie_authorization:
        raise RequiresLoginException

app.include_router(
    files.router,
    tags=["files"],
    dependencies=[Depends(get_cookie_authorization)]
)
```
This works now for all the other routers which I include. It doesn't make sense to use it as a Dependency for including the **auth.py** file because then I cannot login/register ect. Before I used this for custom superuser routes:
```
app.include_router(
    auth_admin.router,
    tags=["auth_admin"],
    dependencies=[Depends(fastapi_users.get_current_superuser)]
)
```
Is it possible that I can use my exception handler in the auth.py as well? I tried it but the routers then I get this error:
`AttributeError: 'APIRouter' object has no attribute 'exception_handler'`

Or can I overwrite the exception which throws me the` {"detail":"Unauthorized"} `error? Or is this smth that should not be done with fastapi/fastapi users?

Thanks in advance for your help!

**Comment by Harrison88** [comment]
Hi @hannawagner!

I'm not 100% sure I understand your question, but I think you should be able to do this using a custom exception handler. The following code, which I mostly got from [the FastAPI docs](https://fastapi.tiangolo.com/tutorial/handling-errors/#re-use-fastapis-exception-handlers), should do what you're asking.
```python
from fastapi import status
from fastapi.exception_handlers import http_exception_handler
from starlette.exceptions import HTTPException as StarletteHTTPException

@app.exception_handler(StarletteHTTPException)
async def custom_http_exception_handler(request, exc):
    # FastAPI-Users returns a 401 error when user is not logged in, so we catch that one and redirect.
    if exc.status_code == status.HTTP_401_UNAUTHORIZED:
        return RedirectResponse(url='/login-form')
    # If it's a different status code, use the default error handler.
    return await http_exception_handler(request, exc)
```

**Comment by hannawagner** [comment]
Hi @Harrison88 !
Thank you for your reply - this actually solved my problem - thank you!! 👍
