### ISSUE TITLE
Umongo for mongoDB backend.

### ISSUE THREAD

**Issue by prostomarkeloff** [frankie567/fastapi-users#43]
Hello! What about [umongo](https://github.com/Scille/umongo) support in this library? Raw mongodb looks bad for me, and umongo helps in use mongodb.

**Comment by frankie567** [comment]
Why not! I don't know that library but I'll look into it. Is it widely used in Python/Mongo based projects?

**Comment by prostomarkeloff** [comment]
Yes, it's only one library with async support for mongo

**Comment by frankie567** [comment]
The way I understand it, umongo is an object-manager built on top of the official wrappers. I see it's compatible with `motor`, which is the official async wrapper we already use.

I understand your point, it's the same as the potential need of SQLAlchemy ORM support. I'll consider it.

**Comment by prostomarkeloff** [comment]
Plan work on it this weekend or later
