### ISSUE TITLE
AssertionError: Unknown path convertor 'uuid'

### ISSUE THREAD

**Issue by FMajesty** [frankie567/fastapi-users#504]
Updated to `0.5.1` version and got this error:
```
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 107, in compile_path
    ), f"Unknown path convertor '{convertor_type}'"
AssertionError: Unknown path convertor 'uuid'
```

**Comment by frankie567** [comment]
Could you do a `pip freeze` and give the version of `fastapi` and `starlette`?

**Comment by FMajesty** [comment]
```
starlette = "0.13.6"
fastapi = "0.63.0"
```

**Comment by frankie567** [comment]
Sorry, I can't reproduce the issue, even on a clean setup (see https://repl.it/@frankie567/fastapi-users-example). Are you sure your virtual environment is correctly loaded and setup?
