### ISSUE TITLE
Problem get user

### ISSUE THREAD

**Issue by ScrimForever** [frankie567/fastapi-users#510]
module 'fastapi_users' has no attribute 'current_user'

user: User = Depends(fastapi_users.current_user()) 

fastapi-users 5.1.0

**Comment by frankie567** [comment]
I think I get what's wrong here: `fastapi_users` is not the module here but the variable you defined, which is an instance of `FastAPIUsers`.

**Comment by ScrimForever** [comment]
My fault. Resolved !

**Comment by rbracco** [comment]
I am getting this error as well and have tried the following things

1. using `Depends(FastAPIUsers.current_user())` as I think is suggested in the reply here, which gives the same error `AttributeError: 'FastAPIUsers' object has no attribute 'current_user'` 
2. using `Depends(fastapi_users.current_user())` as is suggested in the docs, where `fastapi_users` is the instance of `fastapi_users` as created in the docs by calling `FastAPIUsers`
3. importing `fastapi_users`, changing the name of the instance, and then using `Depends(fastapi_users.current_user())` 

All 3 of these result in a variation of that same attribute error (none of them have the attribute `current_user`. What am I doing wrong here?

**Comment by frankie567** [comment]
The way you describe in point 2 is definitely the way to go.

My guess is that you didn't upgrade to 5.1.0, that introduced this new dependency.

If you are in an older version, you have to use the now-deprecated ones: https://frankie567.github.io/fastapi-users/usage/dependency-callables/#deprecated

**Comment by rbracco** [comment]
Thank you for the help, this is most likely it, I don't have users yet so I should be able to upgrade and try it out.
