### ISSUE TITLE
Calls to deprecated user getters

### ISSUE THREAD

**Issue by MatthewScholefield** [frankie567/fastapi-users#515]
## Describe the bug

In the users routes (ie. `/users/me`) which are defined in `fastapi_users/router/users.py`, it uses dependencies like `authenticator.get_current_verified_user` causing `fastapi-users`'s own deprecation message:

```
fastapi/dependencies/utils.py:550: DeprecationWarning: Call to deprecated function (or staticmethod) get_current_active_user. (You should call `current_user` with your own set of parameters. See: https://frankie567.github.io/fastapi-users/usage/dependency-callables/) -- Deprecated since version 5.1.0.
    solved = await call(**sub_values)
```

**Comment by frankie567** [comment]
Obviously, I forgot to change it 😅 Good catch, thanks!
