### ISSUE TITLE
Tortoise ORM support

### ISSUE THREAD

**Issue by prostomarkeloff** [frankie567/fastapi-users#54]
At the moment tortoise-orm is growing up and i think it's good reason for adding it. I plan start work of it soon.

**Comment by prostomarkeloff** [comment]
@frankie567 what should i do when user already created? tortoise can raise exception about it

**Comment by prostomarkeloff** [comment]
But i have the another problem. Tortoise doesn't have a simple `String` field. It provides a `CharField` which must have a `max_length`. Which value should i set in model field?

**Comment by prostomarkeloff** [comment]
Also, i wanna ask you about `id` field. Why string? I think we should convert it to integer.

**Comment by frankie567** [comment]
What we do usually in SQL when don't know in advance the length of the data, is to put the maximum possible length for a `CharField`, i.e. **255** (`VARCHAR(255)` in pure SQL).

The `id` is a string for a very good reason: it's an UUID, and not an auto-increment integer. This pattern is becoming more popular for several reasons: it's universally unique and independent of the environment. This means that you can generate the ID client-side (useful for example for an offline mobile apps) without having to query first the database.

This is handled automatically by the Pydantic model:

https://github.com/frankie567/fastapi-users/blob/f0178d0e0d2b268cd97fa0a3b2d099143083cfda/fastapi_users/models.py#L17-L19

**Comment by prostomarkeloff** [comment]
I think we should add `orm_mode` in pydantic config because without it, I can't return a tortoise model as python dict.
