### ISSUE TITLE
Default users table name is usertables

### ISSUE THREAD

**Issue by sid3r** [frankie567/fastapi-users#540]
I've just tested the package and it's working fine, the code on the docs is clear and behaves almost as expected but I came across this anomaly: the default table name for users is **usertables**
any idea why it's the case? is there a way to specify a table name for users table?

## To Reproduce

The code from the docs: configuration > sqlalchemy
[configuration-databases-sqlalchemy](https://frankie567.github.io/fastapi-users/configuration/databases/sqlalchemy/)

## Expected behavior

The table name should simply be **user**

## Configuration
 - Python version : 3.9
 - FastAPI version : 0.63.0
 - FastAPI Users version : 5.1.0

**Comment by frankie567** [comment]
Hello!

Sorry, I can't reproduce it with the example given in the documentation. Tried both with SQLite and PostgreSQL, the table was correctly named `user`. Are you sure you didn't override the `__tablename__` property on the SQLAlchemy table class?
