### ISSUE TITLE
Unable to use with both Routers and MongoDB

### ISSUE THREAD

**Issue by hamx0r** [frankie567/fastapi-users#550]
## Describe the bug

[Details in this StackOverflow question](https://stackoverflow.com/questions/65930477/how-can-i-use-fastapi-routers-with-fastapi-users-and-mongodb).   Essentially, fastapi-users relies on a MongoDB client instance, which could be set up globally in one's `main.py`.  However, if I want to split up my app into Router files, each file would need to be able to get this MongoDB Client object (rather than making a new one) to ensure it's all working in the same thread.  This would be done using a FastAPI `startup` trigger.   Because such Router endpoints rely on fastapi-users for auth, then I need to somehow instantiate that in main.py too, which doesn't yet have access to a DB client object since it won't be made until the app has started up. 

## To Reproduce

1. Make app with Routers
2. Ensure each router relies on fastapi-users
3. Use `startup` trigger to make MongoDB client
4. Observe chaos

## Expected behavior

Allow `FastAPIUsers()` to take a DB-contention-generating function rather than a DB connection itself (ie a sort of promise)

## Configuration
 - Python version : 3.9
 - FastAPI version : 0.63.0
 - FastAPI Users version : 5.0.0

**Comment by frankie567** [comment]
Well, what you could do is just to move all the MongoDB initialization logic in a separate module, and import it whenever you need it. I've created a working Repl.it example to show you:

https://repl.it/@frankie567/fastapi-users-modular-mongodb
