### ISSUE TITLE
Cannot access /docs because of "TypeError: Object of type 'Depends' is not JSON serializable"

### ISSUE THREAD

**Issue by alexferrari88** [frankie567/fastapi-users#563]
## Describe the bug

When following the steps in [Dependency callables](https://frankie567.github.io/fastapi-users/usage/dependency-callables/#dependency-callables) from the website to [get the current active superuser](https://frankie567.github.io/fastapi-users/usage/dependency-callables/#get-the-current-active-superuser), I can no longer check the /docs page as I get "Failed to load API definition." and the console reports the error `TypeError: Object of type 'Depends' is not JSON serializable`

## To Reproduce

My code (just the relevant part) looks like this:

```python
fastapi_users = FastAPIUsers(
    models.user_db,
    auth.auth_backends,
    models.User,
    models.UserCreate,
    models.UserUpdate,
    models.UserDB,
)

current_user = fastapi_users.current_user(active=True, verified=True)

@app.get("/alerts", response_model=List[schemas.Alert])
async def get_alerts(
    skip: int = 0, limit: int = 100, dependencies=[Depends(current_user)]
):
    return await crud.get_alerts(skip=skip, limit=limit)
```

This problem started happening just as I have added the Depends part.

## Expected behavior

I expect the /docs page of my API to load

## Configuration
 - Python version : 3.9.1
 - FastAPI version : 0.63.0
 - FastAPI Users version : 5.1.2

**Comment by frankie567** [comment]
Hi there!

You put the `dependencies` argument at the wrong place (see https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-in-path-operation-decorators/). If you want it at the router level, it should be:

```py
@app.get("/alerts", response_model=List[schemas.Alert], dependencies=[Depends(current_user)])
async def get_alerts(skip: int = 0, limit: int = 100):
    return await crud.get_alerts(skip=skip, limit=limit)
``` 

Or if you wish to have the user object at hand:

```py
@app.get("/alerts", response_model=List[schemas.Alert])
async def get_alerts(skip: int = 0, limit: int = 100, user = Depends(current_user)):
    return await crud.get_alerts(skip=skip, limit=limit)
```

**Comment by alexferrari88** [comment]
Thank you @frankie567 !
What a dumbass I've been hahaha

Great work on the plugin btw!
