### ISSUE TITLE
TortoiseUserDatabase:bulk_create possibly crashing

### ISSUE THREAD

**Issue by Benoye** [frankie567/fastapi-users#591]
## Describe the bug

In OAuth2 login process, oauth_accounts are not created into the database, using Tortoise ORM. Note that the user creation/update works fine, implying that the `bulk` operation is the problem (see next section).

## To Reproduce

When using OAuth2 routers with Tortoise, the calls in `fastapi_users.db.tortoise.py` are failing.

__line 121__
```
await self.oauth_account_model.bulk_create(oauth_account_objects)
```

__line 142__
```
await self.oauth_account_model.bulk_create(oauth_account_objects)
```

The  following error occurs
```
asyncpg.protocol.protocol.CoreProtocol._bind_execute_many_more StopIteration
```

I have been able to temporarily fix the problem by usign the standard `create()` call rather than the `bulk_create`.

## Expected behavior

Creation/update of the oauth_accounts should work.

## Configuration

 - Python version : 3.7.9
 - FastAPI version : 0.63.0
 - FastAPI Users version : 5.1.3
 - Tortoise ORM version : 0.17.1
 - asyncpg version : 0.22.0
 - uvloop version : 0.15.2
 - PostGres DB version : 12 (running in AWS RDS)

### FastAPI Users configuration

Using the one from the docs with no modification on the models

## Additional context

DB is AWS RDS PostGres database
Service is running in a Kubernetes cluster

**Comment by frankie567** [comment]
Hi @Benoye,

Thank you for the detailed bug report. Unfortunately, I can't reproduce it on a regular PostgreSQL database on Docker. Could you try also on a local PostgreSQL database?

I suspect an issue with RDS and asyncpg here. Maybe this is linked with this issue: https://github.com/MagicStack/asyncpg/issues/700 It seems fixed but not released yet.

**Comment by Benoye** [comment]
Hi @frankie567 thank you for your quick response !
I think you are right, it tested fine on a local PostGreSQL database..
Thanks for finding the link to the issue on asynpg, it is exactly the problem !

I am closing this issue, given that it is not on your side :)
