### ISSUE TITLE
Backref not working at route users/me

### ISSUE THREAD

**Issue by Master-Y0da** [frankie567/fastapi-users#600]
**Using fastapi-users 3.0.6 and tortoise orm 0.16.17**
I have been stuck by almost a week trying to solve this problem and now it seems to be a bug, so I'm leaving evidence. 

I want to access the route **users/me** and append some extra data from a couple of relations I created, these are:

**Tortoise models**    
    
    class UserModel(TortoiseBaseUserModel):

     nombre = fields.CharField(max_length=100)
     apellidos = fields.CharField(max_length=100)
     fecha_nacimiento = fields.DateField(default=None)
     telefono = fields.CharField(max_length=20)
     rut = fields.CharField(max_length=10)
     cargo = fields.CharField(max_length=30)

    class Rol(models.Model):

      id = fields.UUIDField(pk=True)
      nombre = fields.CharField(max_length=100)

    class Permiso(models.Model):

     id = fields.UUIDField(pk=True)
     nombre = fields.CharField(max_length=100)

    class Auth_Rol_Permiso(models.Model, TimestampMixin): -->Relational table between user,permiso and rol classes

     id = fields.UUIDField(pk=True)
     rol = fields.ForeignKeyField('models.Rol', related_name="auth_rol", on_delete=fields.CASCADE)
     permiso = fields.ForeignKeyField('models.Permiso', related_name="auth_permiso", on_delete=fields.CASCADE)
     user = fields.ForeignKeyField("models.UserModel", related_name="auth_user", on_delete=fields.CASCADE)

 So, for Pydantic User schema, I created this:

    class User(fastapi_users_model.BaseUser):
     nombre: str
     apellidos: str
     fecha_nacimiento: date
     telefono: str
     rut: str
     cargo: str
     auth_user: List[UserPermission]  --> Backref for getting permiso and rol relation data

    class Permisoo(BaseModel):
     id: UUID
     nombre: str

    class UserPermission(BaseModel):
     permiso: Optional[Permisoo]
     created_at: datetime
     rol: Optional[Dict[str, Any]]

The problem comes when I try to get data from route **users/me**, this is the response:

![captura](https://user-images.githubusercontent.com/10148942/114432580-d9ff9880-9b8e-11eb-832c-03a42270e45e.png)

But if I go into a custom endpoint that I create for getting rol class, it's working and getting all data without problems!!...I think maybe the problem is that rol pydantic schema is generated by tortoise, with this function -> **pydantic_model_creator**, like this:

`rol_out = pydantic_model_creator(Rol, name="RolOut")`

Anyway, this is the result of getting rol class(working fine):
![captura_1](https://user-images.githubusercontent.com/10148942/114433484-e2a49e80-9b8f-11eb-8d0d-c89e28f6cacd.png)

this doesn't make any sense to me, so I hope you can help me, thanks for your time.

**Comment by frankie567** [comment]
Hi @lvar,

I had the chance to study this a bit further, and it seems indeed that the interaction between Pydantic and Tortoise models is a bit more complex that I implemented in the library. I'll have to revisit the database adapter.

For the record, I put here my experiment. FastAPI-Users need to use the `from_tortoise_orm` utilities.

```py
from datetime import datetime
from typing import List

from tortoise import fields, Tortoise, run_async
from tortoise.contrib.pydantic import PydanticModel
from tortoise.models import Model
from pydantic import BaseModel


class Permission(Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=255)


class UserPermission(Model):
    id = fields.IntField(pk=True)
    created_at = fields.DatetimeField(auto_now_add=True)
    user = fields.ForeignKeyField("models.User", related_name="user_permissions")
    permission = fields.ForeignKeyField("models.Permission")


class User(Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=255)


class PermissionSchema(PydanticModel):
    id: int
    name: str

    class Config:
        orig_model = Permission
        orm_mode = True


class UserPermissionSchema(PydanticModel):
    id: int
    created_at: datetime
    permission: PermissionSchema

    class Config:
        orig_model = UserPermission
        orm_mode = True


class UserSchema(PydanticModel):
    id: int
    name: str
    user_permissions: List[UserPermissionSchema]

    class Config:
        orig_model = User
        orm_mode = True


async def run():
    await Tortoise.init(db_url="sqlite://:memory:", modules={"models": ["__main__"]})
    await Tortoise.generate_schemas()

    p1 = await Permission.create(id=1, name="Permission 1")
    p2 = await Permission.create(id=2, name="Permission 1")
    p3 = await Permission.create(id=3, name="Permission 1")

    user = await User.create(id=1, name="jdoe")

    await UserPermission.create(id=1, user=user, permission=p1)
    await UserPermission.create(id=2, user=user, permission=p2)
    await UserPermission.create(id=3, user=user, permission=p3)

    user = await User.get(id=1)

    user_schema = await UserSchema.from_tortoise_orm(user)
    print(user_schema.json())


if __name__ == "__main__":
    run_async(run())
```

Thank you for pointing this out!

**Comment by lvar** [comment]
@frankie567 Glad I could help!!...
I have a question now I see your test code...is there any difference between use:

      from tortoise.contrib.pydantic import PydanticModel
      from pydantic import BaseModel
Or create the pydantic schemas with `pydantic_model_creator` ??? Should I expect the same result independent on which I choose ?

**Comment by frankie567** [comment]
The official way is to use `pydantic_model_creator`, and I think you should stick with it for your own models.

For fastapi-users, I'll have to implement it by hand through `PydanticModel` for technical reasons; but I don't think it's a good idea for the common case.

**Comment by frankie567** [comment]
This should work better with `v6.0.0`. Please review the documentation to update your configuration: https://frankie567.github.io/fastapi-users/configuration/databases/tortoise/#tweak-userdb-model

**Comment by Master-Y0da** [comment]
@frankie567 Good news!!...anyway, I have a long road from version 3 to 6 :) ...greetings!
