### ISSUE TITLE
request-verify-token returns `VERIFY_USER_ALREADY_VERIFIED` error for verified users

### ISSUE THREAD

**Issue by sandalwoodbox** [frankie567/fastapi-users#609]
## Describe the bug

If a user already exists in the database and is verified, `request-verify-token` will return a 400 response with the following content:

```
{"detail":"VERIFY_USER_ALREADY_VERIFIED"}
```

This is not in line with the [documentation](https://frankie567.github.io/fastapi-users/usage/routes/#verify-router), which states:

> To prevent malicious users from guessing existing users in your database, the route will **always return a 202 Accepted response**, even if the user requested does not exist.

## To Reproduce

1. Create & verify a user account
2. send a request to request-verify-token

## Expected behavior

Either the endpoint should always return a 202 Accepted response (even for users who exist & are verified) or the behavior of returning a 400 with `VERIFY_USER_ALREADY_VERIFIED` should be documented.

If the goal is to prevent malicious actors from guessing existing users, it seems like that may apply even if the requested user is already verified, as well. If not, it would be great to have the reasoning why not documented, as well.

## Configuration
 - Python version : 3.7.9
 - FastAPI version : 0.63.0
 - FastAPI Users version : 5.1.2

**Comment by frankie567** [comment]
Thanks @sandalwoodbox! That's indeed an inconsistency between the code and the documentation.

I'll remove the `VERIFY_USER_ALREADY_VERIFIED` error to be consistent.

**Comment by frankie567** [comment]
@all-contributors add @sandalwoodbox for bug
