### ISSUE TITLE
Use relative `tokenUrl` parameter for JWTAuthentication (and docs)

### ISSUE THREAD

**Issue by eddsalkield** [frankie567/fastapi-users#630]
Currently the [JWTAuthentication docs page](https://frankie567.github.io/fastapi-users/configuration/authentication/jwt/) doesn't document the `tokenUrl` parameter, although it does document all its other parameters.

When/if this gets added, it would be worth mentioning that the `tokenUrl` must be relative (i.e. no prefixing '/') if a custom `root_path` is being used within the FastAPI app.  This is because, if an absolute `tokenUrl` is used instead, then the URL of the token route will be relative to the `root_path`, but the URL in the OpenAPI spec (which is derived from `tokenUrl`) will instead be relative to the base of the URL.  Then any front-end which parses the OpenAPI spec for authentication (e.g. Swagger) won't be able to find the correct URL.

This is currently documented [in the FastAPI docs](https://fastapi.tiangolo.com/tutorial/security/first-steps/#fastapis-oauth2passwordbearer) (see first tip), but would be worth mentioning in the FastAPI-Users docs as well.

Also, I think it would be worth changing the default value of `tokenUrl` from `"/token"` to `"token"`, because the relative URL works both without and with a custom `root_path`.  In addition, the [full examples](https://frankie567.github.io/fastapi-users/configuration/full_example/) could be changed to reflect this too.

**Comment by frankie567** [comment]
Thank you for pointing this out, @eddsalkield! I wasn't aware of that subtlety; it seems it has been introduced around July 2020, but I never saw that.

That's indeed something we should mention in the docs!

**Comment by frankie567** [comment]
@eddsalkield I've put up some changes in #636. Would you mind have a look at it and tell me if it sounds okay for you? 🙂

**Comment by eddsalkield** [comment]
Thanks for this - I think this looks good overall.  However, I've left a couple of minor comments in a review for the PR.
