### ISSUE TITLE
Unable to override currently logged in user for tests

### ISSUE THREAD

**Issue by Fingel** [frankie567/fastapi-users#672]
### Discussed in https://github.com/frankie567/fastapi-users/discussions/671

<div type='discussions-op-text'>

<sup>Originally posted by **Fingel** July 28, 2021</sup>
Hello,

When writing tests for an application built with FastAPI and fastapi-users, it would be helpful to be able to override the [dependency callables](https://frankie567.github.io/fastapi-users/usage/dependency-callables.html) in a fixture so that we can test protected routes.

In theory, this can be done with [app.dependency_overrides](https://fastapi.tiangolo.com/advanced/testing-dependencies/#testing-dependencies-with-overrides) provided by Fastapi. And I've had this work fine with a hand written auth backend, but not with fastapi-users.

A fixture would look something like this:

```python
@pytest.fixture
async def basic_user() -> UserDB:
    user_create = UserCreate(
        username='test_user',
        password='test123',
        email='test@example.com',
        is_active=True,
        is_superuser=False,
        is_verified=True
    )

    user = await fastapi_users.create_user(user_create)
    app.dependency_overrides[fastapi_users.current_user] = lambda: user
    yield user
    app.dependency_overrides = {}
    await User.filter(id=user.id).delete()
```

And then you could have a protected route, and test that you are able to access it:

```python
@app.get("/protected-route")
def protected_route(user: User = Depends(fastapi_users.current_user())):
    return f"Hello, {user.email}"

@pytest.mark.asyncio
async def test_protected_route(self, client: AsyncClient, basic_user: User) -> None:
        response = await client.get(app.url_path_for('protected_route'))
        assert response.status_code == status.HTTP_200_OK
```

However, the test fails with 401 unauthorized.

How can we use `dependency_overrides` to achieve this? I've tried overriding several different methods, including `fastapi_users.current_user`, `fastapi_users.authenticator.current_user`, `fastapi_users.get_current_user` to no avail.

I would consider this an essential function to be able to write a tested application, surely someone has gotten this to work?
</div>

**Comment by frankie567** [comment]
As mentioned in #671, I'll investigate this.
