### ISSUE TITLE
Unable to get the id field with beanie

### ISSUE THREAD

**Issue by FaresAhmedb** [frankie567/fastapi-users#674]
[Beanie](https://github.com/roman-right/beanie) aliases the `_id` field in mongodb to `id` by [default](https://roman-right.github.io/beanie/tutorial/defining-a-document/#the-id-field)
So Beanie produces something like this on a simple query `dict(await UserDB.find_one())`:
```python
{
    'email': 'mail@example.com',
    'hashed_password': 'HASHED_PASS',
    'id': ObjectId('MONGODB_ID'),
    'is_active': True,
    'is_superuser': True,
    'is_verified': True
}
```

Using beanie's [solution](https://roman-right.github.io/beanie/tutorial/defining-a-document/#the-id-field) to override the default behavior is not possible since FastAPI-Users is using motor.

There's some possible solutions that has come to my mind:
- Providing beanie as a separate database with something like `MongoDBBeanieUserDatabase` or `BeanieUserDatabase`
- Using something like `user_id` instead of `id` but this is obviously not a good solution
- Monkey patch FastAPI-Users Pydantic models to use beanie's way to override the default behavior

I would love to hear your thoughts.. and thanks for the beautiful library :)

**Comment by FaresAhmedb** [comment]
Another solution I has came up with to be able to get the object id created by 
mongodb to get important info like document creation date:

```python
from pydantic import Field, UUID4, BaseModel
from typing import Optional
from beanie import Document, PydanticObjectId
# To create the ObjectId inside of Python
from bson import ObjectId

class UserDB(Document, User, BaseUserDB):
    # ...
    id: Optional[UUID4] = Field(alias="id")
    # We could use `_id` instead of `obj_id` but unfortunately
    # Pydantic doesn't allow attributes like `_foo`, `__bar__` to be public
    obj_id: Optional[PydanticObjectId] = Field(alias="_id", default_factory=ObjectId)
    # however it would look like this:
    # _id: Optional[PydanticObjectId] = Field(alias="_id")
    # just like the id attribute.

    # ...
    class Collection:
        name = "users"

    # Here we are kinda monkey patching FastAPI-Users to
    # insert aliases (e.g. `_id`) instead of public attribute (e.g. `obj_id`)
    def dict(self, **kwargs):
        kwargs.setdefault("by_alias", True)
        return BaseModel.dict(self, **kwargs)
    # We could use FastAPI Extra Models technique to do the same thing
    # but I think this is cleaner since everything is in 1 object
```

Hi @frankie567 ! Should I mark this issue as solved?

**Comment by frankie567** [comment]
Hi @FaresAhmedb!

Thank you for the investigations and the proposed solutions. I don't know Beanie much but it looks like inheriting both from `Document` and `BaseUser` is the right way to go.

Obviously, the best way would be to implement an adapter for Beanie so that it works out of the box without having to use Motor directly. I'll consider it!

**Comment by galvakojis** [comment]
Hello, I am not sure where is a problem? I can't use old `users` collections with newest version.

Do I need to use some kind of migration, or what, at this moment I am lost
