### ISSUE TITLE
Automatic documentation doesn't discover authentication method

### ISSUE THREAD

**Issue by frankie567** [frankie567/fastapi-users#68]
Following the implementation of multiple auth backends, I didn't find a way yet to make OpenAPI discover the authentication method (even at least one).

I guess we have to go deeper in fastapi implementation to understand how to do this.

**Comment by jet10000** [comment]
https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/#authenticate

**Comment by MariusMez** [comment]
My 2cents as I don't know what you've tried or not.

From what I've seen, to display the "Authorize" button, OpenAPI needs an 'Authorization' header. (https://stackoverflow.com/questions/32910065/how-can-i-represent-authorization-bearer-token-in-a-swagger-spec-swagger-j).

In FastAPI, it seem's open-api schema are generated 'using routes', each route can integrate is own Security_schemes (https://github.com/tiangolo/fastapi/blob/4e8080f29013dcb6850518bb9011bf82c9081828/fastapi/openapi/utils.py)

Here is a test: https://github.com/tiangolo/fastapi/blob/025b38df40a18f94322fab445aee13024fe783da/tests/test_security_oauth2_password_bearer_optional.py 

Using this kind of fastapi class 'OAuth2PasswordBearer' injected with Depends() (or Security()) in routers seems to add oauth2 security scheme in the open-api schema generation resulting in the 'Authorize' button showing is face.

```
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/token", auto_error=False)
async def get_current_user(token: str = Depends(oauth2_scheme)):
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
```
[...]

But how/where to integrate/mimic this inside fastapi-users ?

**Comment by frankie567** [comment]
Thank you @MariusMez for digging through this 👍 The problem here is that we "break" the dependency chain for various reasons (support of several authentication backends, configuration...).

Our best bet would be if we could hook into the OpenAPI schema generation to add our own logic 🤔

**Comment by mrchoke** [comment]
I hard code in 
fastapt_users/autgebtication/__init__.py

```
from fastapi import Depends, HTTPException

async def get_current_active_user(self, request: Request ,check = Depends(OAuth2PasswordBearer(tokenUrl='/auth/users/login/thaijo21', auto_error=False))) -> BaseUserDB:
        user = await self.get_current_user(request)
        if not user.is_active:
            raise self._get_credentials_exception()
        return user
```

I add this
`check = Depends(OAuth2PasswordBearer(tokenUrl='/auth/users/login/thaijo21', auto_error=False))`

and in 
fastapt_users/autgebtication/jwt.py

```

async def get_login_response(self, user: BaseUserDB, response: Response) -> Any:
        token = await self._generate_token(user)
        #return {"token": token}
        return {"access_token": token}

```
I return **access_token** instead of **token**

Then I can use auth on fastapi swagger ui.

**Note**. _I use router prefix as /auth and jwt name as thaijo21_

![ภาพ](https://user-images.githubusercontent.com/3403645/78977076-b059fe80-7b41-11ea-8fc5-f843d7438157.png)

but I can't apply to your jwt class. T_T

**Comment by martincolladofab** [comment]
Currently fastapi-users uses httpx-oauth for the OAuth flow, would it be interesting perhaps to add the use of the authlib library to facilitate this flow?
Examples: https://github.com/authlib/demo-oauth-client
Documentation: https://docs.authlib.org/en/latest/client/fastapi.html

**Comment by frankie567** [comment]
Hi @martincolladofab! I deliberately put `authlib` aside because of its license : https://authlib.org/plans
You cannot use it for free for commercial projects, which is a totally no-go for me.

That's why I created `httpx-oauth` which is a simple and pure async OAuth client.

**Comment by martincolladofab** [comment]
wow! I did't know about the pricing licence! I think that it's no-go for alot of people hehe
