### ISSUE TITLE
Using TextField as user.id index is a bad idea.

### ISSUE THREAD

**Issue by grigi** [frankie567/fastapi-users#77]
Specifically referring to: https://github.com/frankie567/fastapi-users/blob/master/fastapi_users/db/tortoise.py#L11

I'm sorry I got here so late (via #59 from https://github.com/tortoise/tortoise-orm/issues/246), but a `TextField` is a really bad primary key.

It is a very-large text field, as in a gigabyte large.  Also MySQL will at best index the first 1023 bytes (about 255 Unicode chars) and then just stop indexing.
So this is wide open for abuse, and bugs.
It will also perform terribly as both MySQL and PostgreSQL will only ever store a reference to an external block for the row.

A better, and preferable option would be `fields.CharField(max_len=255, pk=True)`

**Comment by frankie567** [comment]
Wow 😱Thank you for pointing this out @grigi, I didn't pay enough attention when I merged this PR. Of course, this is bad. I'll change it ASAP.

**Comment by grigi** [comment]
Wow, that was fast!

**Comment by frankie567** [comment]
Didn't want to keep something *that* huge too long in the codebase 😅Thank you very much 👍

**Comment by frankie567** [comment]
@all-contributors add @grigi  for bug
